from pathlib import Path
from django.conf import settings
from django.urls import path,re_path
from django.views.static import serve
from control import views,monitoring_views as monitor,service_entry_views as service_entry
urlpatterns=[path("api/v1/service-entry/services",service_entry.services),path("api/v1/service-entry/services/<uuid:pk>",service_entry.services),path("api/v1/service-entry/options",service_entry.options),path("api/v1/service-entry/templates/services.csv",service_entry.template),path("api/v1/service-entry/imports/<str:action>",service_entry.imports),path("api/v1/service-entry/services/<uuid:pk>/export",service_entry.export),path('api/v1/monitoring/clusters',monitor.clusters),path('api/v1/monitoring/options',monitor.options),path('api/v1/monitoring/clusters/<uuid:pk>/source',monitor.source),path('api/v1/monitoring/imports/<str:action>',monitor.imports),path('api/v1/monitoring/templates/<str:kind>.csv',monitor.template),path('api/v1/catalog/endpoints/<uuid:pk>/runtime-members',views.runtime_members),path('api/v1/session',views.session),path('api/v1/catalog/businesses/<uuid:pk>/service-bindings',views.relations,{'kind':'bindings'}),path('api/v1/catalog/<str:collection>',views.catalog),path('api/v1/catalog/<str:collection>/<uuid:pk>',views.catalog),path('api/v1/gateway/keys',views.catalog,{'collection':'keys'}),path('api/v1/gateway/keys/<uuid:pk>',views.catalog,{'collection':'keys'}),path('api/v1/gateway/keys/<uuid:pk>/model-grants',views.relations,{'kind':'grants'}),path('api/v1/integrations/status',views.status),path('api/v1/integrations/<str:collection>',views.catalog),path('api/v1/integrations/<str:collection>/<uuid:pk>',views.catalog),path('api/v1/topology',views.topology_view),path('api/v1/screens/<str:kind>',views.screens),path('api/v1/telemetry/endpoints/<uuid:pk>/history',views.history),path('api/v1/audit-events',views.audit_events),path('api/v1/healthz',views.health),path('api/v1/readyz',views.health,{'ready':True}),path('healthz',views.health),path('readyz',views.health,{'ready':True})]
if settings.LOCAL:
    def frontend(request,path='index.html'):
        if not path or path.endswith('/'):path+='index.html'
        return serve(request,path,document_root=Path(settings.BASE_DIR).parent/'frontend',show_indexes=False)
    urlpatterns += [re_path(r'^(?P<path>(?:gateway|screen)/.*)$',frontend),path('',frontend,{'path':'screen/index.html'})]
