(()=>{'use strict';
const A=ControlAPI,e=A.escape,main=document.querySelector('#main');let session=null,catalog={},route='overview',key=null,grants=[],epoch=0,graph=null,filter='',overviewData=null,overviewTeam='',overviewCluster='',overviewIntent='';
const resources={teams:'团队',businesses:'业务',models:'模型',services:'服务','pd-groups':'PD 组',endpoints:'Endpoint',clusters:'集群',keys:'API Key'};
const typeResource={team:'teams',business:'businesses',model:'models',service:'services',pd_group:'pd-groups',endpoint:'endpoints',cluster:'clusters',key:'keys'};
const path=r=>r==='keys'?'/api/v1/gateway/keys':'/api/v1/catalog/'+r;
const empty=(title,text)=>`<div class="empty"><strong>${e(title)}</strong>${e(text)}</div>`;
const warning='<div class="warning">仅管理配置，未验证执行端生效。Key 生效状态：NOT_CONNECTED；保存、暂停或授权变更不会宣称已阻断真实请求。</div>';
const name=(r,id)=>catalog[r]?.find(x=>x.id===id)?.name||'未关联';
const canWrite=()=>session?.can_write===true;
function toast(text){const t=document.querySelector('#toast');t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3500);}
function fail(err){let el=main.querySelector('.error');if(!el){el=document.createElement('div');el.className='error';el.setAttribute('role','alert');main.prepend(el);}el.textContent=err.payload?.error?.code==='VERSION_CONFLICT'?'版本冲突：数据已被其他用户修改。请刷新并核对后重新保存；当前输入未被覆盖。':err.message+(err.payload?.error?.details?.references?'：'+JSON.stringify(err.payload.error.details.references):'');}
function head(title,sub){return `<div class="page-head"><div><h1>${e(title)}</h1><p>${e(sub)}</p></div><span class="sync-status">目录可用环境：${e(session?.environments?.join(' / ')||'')} · 统一管理目录</span></div>`;}
function accessNotice(){catalog={};main.innerHTML='<section class="panel pad"><h1>接口暂不可用</h1><p>请检查服务接口后刷新此页。</p></section>';}

async function all(r){let items=[],cursor=null;for(let page=0;page<100;page++){const v=await A.request(path(r)+'?limit=100'+(cursor?'&cursor='+encodeURIComponent(cursor):''));items.push(...v.data.items);cursor=v.data.next_cursor;if(!cursor)return items;}throw new Error('目录超过当前浏览器有界加载上限，请缩小环境范围');}
async function load(){if(serviceController&&!serviceController.confirmLeave())return false;if(catalogController&&!catalogController.confirmLeave())return false;callflowController?.destroy();callflowController=null;monitorController?.destroy();monitorController=null;manualImportController?.destroy();manualImportController=null;catalogController?.destroy();catalogController=null;serviceController?.destroy();serviceController=null;const mine=++epoch;main.innerHTML=head('正在加载统一目录…','首帧指标状态未知');try{session=await A.ensureAccess();const entries=await Promise.all(Object.keys(resources).map(async r=>[r,await all(r)]));if(mine!==epoch)return false;catalog=Object.fromEntries(entries);await navigate(route,route==='catalog'?{id:query.get('service')||undefined,environment_code:query.get('environment_code')||undefined}:undefined);return true;}catch(err){if(!session)accessNotice();fail(err);return false;}}
function overview(){return head('AI 网关资源关系总览','团队、业务、授权模型与实际登记的部署关系')+`<section class="metrics">${['teams','businesses','models','endpoints','clusters'].map(r=>`<div class="metric ${r==='teams'?'accent':''}"><small>${resources[r]}</small><strong>${catalog[r].length}</strong><span>已登记 · 非运行健康数</span></div>`).join('')}</section>`+warning+`<section class="panel"><div class="panel-head"><div><h2>统一主数据链路</h2><p>选择对象进入资源映射；所有连接由后端真实关系返回。</p></div><button class="btn" data-route="catalog">录入资源 / 编辑关系 ↗</button></div><div class="chain">${['team','business','key','model','service','pd_group','cluster'].map(t=>{const r=typeResource[t];return `<button class="chain-card" data-map-type="${t}"><span>${e(t.toUpperCase())}</span><b>${resources[r]}</b><em>${catalog[r].length} 个已登记</em></button>`;}).join('')}</div></section>${overviewGraphShell()}<section class="panel overview-map"><div class="panel-head"><div><h2>授权与运行实例映射</h2><p>每行对应一条 Key × 模型 × Endpoint × 运行成员关系；缺少部署时保留配置行。</p></div><span class="pill neutral">只读总览 · 非运行健康状态</span></div><div class="toolbar overview-toolbar"><input id="search" class="search" aria-label="搜索授权映射" placeholder="搜索团队 / Key / 模型 / 地址引用 / Pod / 集群 / 节点" value="${e(filter)}"><select id="overview-team" aria-label="筛选团队"><option value="">全部团队</option>${catalog.teams.map(x=>`<option value="${e(x.id)}" ${x.id===overviewTeam?'selected':''}>${e(x.name)}</option>`).join('')}</select><select id="overview-cluster" aria-label="筛选集群"><option value="">全部集群</option>${catalog.clusters.map(x=>`<option value="${e(x.id)}" ${x.id===overviewCluster?'selected':''}>${e(x.name)}</option>`).join('')}</select><select id="overview-intent" aria-label="筛选配置意图"><option value="">全部意图</option><option value="ACTIVE" ${overviewIntent==='ACTIVE'?'selected':''}>ACTIVE</option><option value="SUSPENDED" ${overviewIntent==='SUSPENDED'?'selected':''}>SUSPENDED</option><option value="DISABLED" ${overviewIntent==='DISABLED'?'selected':''}>目录停用</option></select></div><div id="overview-rows">${overviewRows()}</div></section>`;}
function overviewRows(){
 if(!overviewData)return empty('正在读取授权关系','以 Key 配置和授权的同一版本生成映射。');
 if(overviewData.error)return `<div class="error" role="alert">授权映射读取失败：${e(overviewData.error)}。请刷新后重试；此处不展示不完整结果。</div>`;
 const q=filter.trim().toLowerCase(),rows=overviewData.rows.filter(row=>{
  const {key,team,model,service,endpoint,member,cluster,note}=row;
  if(overviewTeam&&key.team_id!==overviewTeam)return false;
  if(overviewCluster&&endpoint?.cluster_id!==overviewCluster)return false;
  if(overviewIntent&&(overviewIntent==='DISABLED'?key.enabled!==false:key.enabled===false||key.desired_status!==overviewIntent))return false;
  return !q||[team?.name,team?.code,key.name,key.masked_label,model?.name,service?.name,endpoint?.address_ref,endpoint?.name,member?.pod_name,member?.node_name,cluster?.name,note].some(x=>String(x||'').toLowerCase().includes(q));
 });
 const notice=(overviewData.truncated?`<div class="overview-limit" role="status">仅读取前 ${GatewayOverviewMapping.MAX_KEYS} 个 Key 的授权，共 ${overviewData.totalKeys} 个 Key；结果已截断，不代表全量。</div>`:'')+(overviewData.rowsTruncated?`<div class="overview-limit" role="status">映射最多展示 ${GatewayOverviewMapping.MAX_ROWS} 行，结果已截断，不代表全量。</div>`:'');
 if(!rows.length)return notice+empty('暂无匹配映射',overviewData.totalKeys?'调整筛选条件，或在 Key 配置中检查授权。':'尚未登记 Key 引用。');
 return notice+`<div class="overview-table-scroll"><table class="overview-table"><thead><tr><th>团队</th><th>API Key</th><th>模型</th><th>服务地址引用</th><th>模型 Pod</th><th>集群</th><th>节点</th><th>配置意图</th><th>映射</th></tr></thead><tbody>${rows.map(row=>{
  const {key,team,model,service,endpoint,member,cluster,note}=row;
  const intent=key.enabled===false?'目录停用':key.desired_status==='SUSPENDED'?'SUSPENDED':'ACTIVE';
  const focus=['endpoint','service','model','key','team'].map(type=>({type,item:{endpoint,service,model,key,team}[type]})).find(x=>x.item?.enabled!==false&&x.item?.id&&x.item.name!=='目录不可见');
  return `<tr data-map-row="${e(row.id)}"><td><div class="overview-team"><span class="avatar">${e((team?.name||'?').slice(0,1))}</span><span><b>${e(team?.name||'未关联团队')}</b><small>${e(team?.code||key.environment_code)}</small></span></div></td><td><button class="key-badge" data-key="${e(key.id)}" type="button">${e(key.masked_label)} ↗</button><small class="overview-secondary">${e(key.name)}</small></td><td>${model?`<span class="tag model">${e(model.name)}</span>`:'<span class="overview-missing">未配置</span>'}</td><td>${endpoint?`<span class="tag ip">${e(endpoint.address_ref||'未登记地址引用')}</span><small class="overview-secondary">${e(service?.name||'')} · ${e(endpoint.role||'')}</small>`:'<span class="overview-missing">未登记</span>'}</td><td class="pod">${e(member?.pod_name||'未登记')}<small class="overview-secondary">${e(member?.namespace||'')}</small></td><td>${cluster?`<span class="tag cluster">${e(cluster.name)}</span>`:'<span class="overview-missing">未登记</span>'}</td><td>${member?.node_name?`<span class="tag node">${e(member.node_name)}</span>`:'<span class="overview-missing">未登记</span>'}</td><td><span class="tag ${intent==='ACTIVE'?'good':intent==='SUSPENDED'?'warn':'bad'}">${e(intent)}</span><small class="overview-secondary">执行端 ${e(key.effective_status||'NOT_CONNECTED')}</small>${!model?.enabled&&model?'<small class="overview-secondary">模型已停用</small>':''}${!service?.enabled&&service?'<small class="overview-secondary">服务已停用</small>':''}${!endpoint?.enabled&&endpoint?'<small class="overview-secondary">Endpoint 已停用</small>':''}${note?`<small class="overview-secondary">${e(note)}</small>`:''}</td><td>${focus?`<button class="overview-map-link" data-focus-type="${focus.type}" data-focus-id="${e(focus.item.id)}">查看 ↗</button>`:'<span class="overview-missing">已停用</span>'}</td></tr>`;
 }).join('')}</tbody></table></div><div class="panel-foot"><span>地址为目录引用，Pod / 节点为登记信息；均不表示已验证健康。</span><span>当前显示 ${rows.length} 条映射${overviewData.truncated||overviewData.rowsTruncated?'（部分结果）':''}</span></div>`;
}
async function loadOverview(mine){
 overviewData=null;const holder=document.querySelector('#overview-rows');if(holder)holder.innerHTML=overviewRows();
 try{
  const [members,result]=await Promise.all([all('runtime-members'),GatewayOverviewMapping.load({keys:catalog.keys,request:A.request,isCurrent:()=>mine===epoch})]);
  if(mine!==epoch||!result)return;
  catalog['runtime-members']=members;
  const mapping=GatewayOverviewMapping.buildRows(catalog,result.snapshots);overviewData={...result,rows:mapping.rows,rowsTruncated:mapping.truncated};
 }catch(err){if(mine!==epoch)return;overviewData={error:err.message||'未知错误'};}
 if(mine===epoch){const target=document.querySelector('#overview-rows');if(target)target.innerHTML=overviewRows();}
}
function keysPage(){return head('API Key 引用管理','保存外部引用、归属与授权配置意图；不签发或展示原始密钥')+warning+`<section class="panel"><div class="panel-head"><h2>已登记 Key</h2>${canWrite()?'<button class="btn primary" id="new-key">＋ 登记 Key 引用</button>':''}</div>${catalog.keys.length?`<table class="catalog-table"><thead><tr><th>名称 / 脱敏标签</th><th>团队</th><th>业务</th><th>环境</th><th>配置意图</th><th>执行状态</th></tr></thead><tbody>${catalog.keys.map(k=>`<tr class="key-row" data-key="${e(k.id)}"><td><b>${e(k.name)}</b><div class="sub">${e(k.masked_label)}</div></td><td>${e(name('teams',k.team_id))}</td><td>${e(name('businesses',k.business_id))}</td><td>${e(k.environment_code)}</td><td>${e(k.desired_status)}</td><td>NOT_CONNECTED</td></tr>`).join('')}</tbody></table>`:empty('尚未登记 Key 引用','先维护团队与业务，再登记已有网关的 Key 引用。')}</section>`;}
function options(r,value,optional=false){return (optional?'<option value="">不关联</option>':'<option value="">请选择</option>')+catalog[r].filter(x=>x.enabled||x.id===value).map(x=>`<option value="${e(x.id)}" ${x.id===value?'selected':''}>${e(x.name)} · ${e(x.environment_code)}${x.enabled?'':' · 目录停用'}</option>`).join('');}
function keyPage(){const k=key||{},write=canWrite(),models=catalog.models.filter(x=>x.environment_code===k.environment_code&&(x.enabled||grants.some(g=>g.model_id===x.id&&g.enabled)));return `<button class="back key-back" data-route="keys">← 返回 Key 列表</button><div class="key-title-row"><div><h1>${k.id?'API Key 配置':'登记 Key 引用'}</h1><p>集中管理目录引用、归属、配置意图与模型授权。</p></div>${k.id?`<span class="key-title-badge">${e(k.masked_label)}</span>`:''}</div>`+warning+`<div class="two-col key-config-layout"><section class="panel pad key-base"><h2>基础配置</h2><form id="key-form">${k.id?`<p class="sub">系统代码：${e(k.code)}</p>`:'<p class="sub">UUID 与稳定代码由服务器生成。</p>'}<div class="form-grid">${[['name','显示名称'],['environment_code','环境代码'],['external_key_ref','外部引用 ID（非原始密钥）'],['masked_label','脱敏标签（含 • 或 *）']].map(([f,l])=>`<label>${l}<input name="${f}" value="${e(k[f]||'')}" required ${f==='environment_code'&&k.id?'readonly':''} ${!write?'disabled':''}>${f==='environment_code'&&k.id?'<small>已有 Key 的环境不可变更</small>':''}</label>`).join('')}<label>所属团队<select name="team_id" required ${!write?'disabled':''}>${options('teams',k.team_id)}</select></label><label>所属业务<select name="business_id" ${!write?'disabled':''}>${options('businesses',k.business_id,true)}</select></label><label>配置意图<select name="desired_status" ${!write?'disabled':''}><option ${k.desired_status==='ACTIVE'?'selected':''}>ACTIVE</option><option ${k.desired_status==='SUSPENDED'?'selected':''}>SUSPENDED</option></select></label></div><label class="key-check"><input type="checkbox" name="enabled" ${k.enabled!==false?'checked':''} ${!write?'disabled':''}> 启用此目录引用</label>${k.id?'<label class="key-check"><input type="checkbox" name="confirm_disable"> 已核对关联影响，确认停用该引用（仅停用时需要）</label>':''}<div class="key-unsupported"><b>访问策略 · 未接入</b><span>RPM、TPM、过期时间和来源限制暂不支持保存或执行。</span></div><div class="form-actions"><button type="button" class="btn" data-route="keys">撤销</button>${write?'<button class="btn primary">保存配置</button>':''}</div></form><p class="sub">记录版本 ${e(k.version||'新建')} · applied_to_data_plane=false</p></section><section class="panel pad key-grants"><h2>模型授权</h2>${k.id?`<form id="grant-form"><div class="grant-list">${models.map(x=>`<label class="grant-card ${grants.some(g=>g.model_id===x.id&&g.enabled)?'selected':''}"><input type="checkbox" name="model_ids" value="${e(x.id)}" ${grants.some(g=>g.model_id===x.id&&g.enabled)?'checked':''} ${!write?'disabled':''}><span><b>${e(x.name)}</b><small>${e(x.code)} · ${e(x.environment_code)}${x.enabled?'':' · 模型已停用'}</small></span><em>${grants.some(g=>g.model_id===x.id&&g.enabled)?'已授权':'未授权'}</em></label>`).join('')||'<p class="sub">当前环境暂无可选模型。</p>'}</div>${write?'<button class="btn key-add-grant" type="button" id="grant-add">＋ 添加模型授权</button><div class="form-actions"><button class="btn primary">保存授权配置</button></div>':''}</form>`:'<p class="sub">先保存 Key 引用，再设置模型授权。</p>'}<p class="sub">授权仅保存到统一管理域，执行端尚未连接。</p></section></div>`;}
let manualImportController=null,monitorController=null,callflowController=null,catalogController=null,serviceController=null;
const mappingModeKey='gateway.mapping.layout.v1';let mappingMode='demo';try{if(localStorage.getItem(mappingModeKey)==='callflow')mappingMode='callflow';}catch{}
function modeControls(){return `<div class="mapping-modes" role="group" aria-label="映射展示模式"><span>展示模式</span><button type="button" data-mapping-mode="demo" aria-pressed="${mappingMode==='demo'}">Demo 图形拓扑</button><button type="button" data-mapping-mode="callflow" aria-pressed="${mappingMode==='callflow'}">调用关系</button></div>`;}
function setMappingMode(mode){if(!['demo','callflow'].includes(mode)||mappingMode===mode)return;mappingMode=mode;try{localStorage.setItem(mappingModeKey,mode);}catch{}document.querySelectorAll('[data-mapping-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mappingMode===mode)));drawGraph();}
let focusType='model',focusId='',mapSearch='',expanded=new Set(),motionPaused=false;
const labels={cluster:'集群',node:'节点',deployment_summary:'Pod 部署汇总',pod:'Pod',runtime_member:'运行成员',endpoint:'Endpoint',pd_group:'P/D 组',service:'服务',model:'模型',key:'授权 Key',business:'业务',team:'调用团队'};
let focusSelections={};
function focusOptions(type,value,initial=false){
 if(typeResource[type])return options(typeResource[type],value);
 if(!['node','pod'].includes(type))return '<option value="">请选择</option>';
 const nodes=(graph?.nodes||[]).filter(n=>n.type===type),items=nodes.map(n=>({id:n.id.slice(n.id.indexOf(':')+1),name:n.name}));
 if(initial&&value&&!items.some(n=>n.id===value))items.unshift({id:value,name:value});
 return items.length?items.map(n=>`<option value="${e(n.id)}" ${n.id===value?'selected':''}>${e(n.name)}</option>`).join(''):'<option value="">当前授权图中无此类对象</option>';
}
const motionPreference=matchMedia('(prefers-reduced-motion: reduce)');
function mappingChoices(){const q=mapSearch.trim().toLowerCase();return Object.entries(typeResource).map(([t,r])=>{const rows=catalog[r].filter(x=>(x.name+' '+x.id+' '+(x.environment_code||'')).toLowerCase().includes(q));return `<details class="map-group" ${q||['model','team'].includes(t)?'open':''}><summary class="map-group-title">${resources[r]} · ${rows.length}</summary>${rows.map(x=>`<button class="map-choice ${focusType===t&&focusId===x.id?'active':''}" data-focus-type="${t}" data-focus-id="${e(x.id)}">${e(x.name)}</button>`).join('')||'<span class="sub">无匹配对象</span>'}</details>`;}).join('');}
function ensureFocus(){if(focusId)return;for(const t of ['service','model',...Object.keys(typeResource)]){const item=(catalog[typeResource[t]]||[]).find(x=>x.enabled);if(item){focusType=t;focusId=item.id;return;}}}
function mappingShell(){ensureFocus();focusSelections={[focusType]:focusId};return head('动态资源映射','选择图形拓扑或调用关系，查看同一范围的配置与部署关系')+`<div class="mapping-layout"><aside class="panel pad mapping-filter"><h2>快速定位</h2><input id="map-search" class="search" placeholder="搜索模型、团队或其他对象" aria-label="搜索完整映射目录" value="${e(mapSearch)}"><div id="map-choices">${mappingChoices()}</div></aside><section class="panel mapping-panel"><form class="focus-form" id="focus-form"><select id="focus-type">${!typeResource[focusType]?`<option value="${e(focusType)}" selected>${e(labels[focusType])}</option>`:''}${Object.keys(typeResource).map(t=>`<option value="${t}" ${t===focusType?'selected':''}>${resources[typeResource[t]]}</option>`).join('')}</select><select id="focus-id" data-focus-kind="${e(focusType)}">${focusOptions(focusType,focusId,true)}</select><button class="btn primary">查看映射</button></form><div class="graph-controls"><button class="btn" type="button" data-entry-focus>配置当前对象 ↗</button><span>缺少连线时，编辑业务服务依赖、Key 授权或部署关系。</span></div>${modeControls()}<div id="graph">${empty('正在查询关系','后端返回真实节点与边，不按相邻列推算连线。')}</div></section></div>`;}

function overviewGraphShell(){return `<section class="panel mapping-panel"><div class="panel-head"><div><h2>资源关联关系图</h2><p>后端返回已登记节点与连接；不表示真实流量。</p></div><button class="btn" data-route="mapping">完整资源映射 ↗</button></div><form class="focus-form" id="overview-focus-form"><select id="overview-focus-type">${Object.keys(typeResource).map(t=>`<option value="${t}" ${t===focusType?'selected':''}>${resources[typeResource[t]]}</option>`).join('')}</select><select id="overview-focus-id">${focusOptions(focusType,focusId)}</select><button class="btn primary">查看关系</button></form>${modeControls()}<div id="graph">${empty('正在读取关联关系','使用正式目录节点与边。')}</div></section>`;}
async function loadOverviewGraph(mine){if(!focusId){const holder=document.querySelector('#graph');if(holder)holder.innerHTML=empty('暂无可用的映射起点','请先在资源录入登记服务或模型。');return;}try{const v=await A.request('/api/v1/topology?focus_type='+encodeURIComponent(focusType)+'&focus_id='+encodeURIComponent(focusId));if(mine!==epoch)return;graph=v.data;drawGraph();}catch(err){if(mine===epoch)fail(err);}}
function graphHTML(){return '<div class="callflow-mount"></div>';}
function drawGraph(){if(!graph)return;const container=document.querySelector('#graph');if(!container)return;callflowController?.destroy();callflowController=(mappingMode==='demo'?GatewayDemoTopology:GatewayCallflow).mount(container,graph,{focusType,focusId,escape:e,endpointRoles:Object.fromEntries((catalog.endpoints||[]).map(x=>['endpoint:'+x.id,x.role])),onFocus:async(type,id)=>{focusType=type;focusId=id;await navigate('mapping');}});}
function renderGraph(){drawGraph();}
async function showGraph(){ensureFocus();callflowController?.destroy();callflowController=null;graph=null;if(['pod','endpoint'].includes(focusType))expanded.add(focusType);const mine=++epoch;main.innerHTML=mappingShell();if(!focusId){document.querySelector('#graph').innerHTML=empty('选择一个映射起点','当前目录为空时，可先点击“录入资源 / 编辑关系”登记资源。');return;}try{const v=await A.request('/api/v1/topology?focus_type='+encodeURIComponent(focusType)+'&focus_id='+encodeURIComponent(focusId));if(mine!==epoch)return;graph=v.data;const selector=document.querySelector('#focus-id');if(selector&&['node','pod'].includes(selector.dataset.focusKind))selector.innerHTML=focusOptions(selector.dataset.focusKind,selector.value);renderGraph();}catch(err){if(mine===epoch)fail(err);}}
async function navigate(next,id){if(serviceController&&!serviceController.confirmLeave())return false;if(catalogController&&!catalogController.confirmLeave())return false;callflowController?.destroy();callflowController=null;monitorController?.destroy();monitorController=null;manualImportController?.destroy();manualImportController=null;catalogController?.destroy();catalogController=null;serviceController?.destroy();serviceController=null;route=next;document.querySelectorAll('[data-route]').forEach(b=>b.classList.toggle('active',b.dataset.route===next));if(next==='mapping'){await showGraph();return true;}epoch++;if(next==='catalog'){const mine=epoch;main.innerHTML=head('资源录入','一次登记整项推理服务，包含业务、模型与全部部署实例')+'<div id="service-entry"></div>';serviceController=GatewayServiceEntry.mount(document.querySelector('#service-entry'),{api:A,escape:e,session,initial:id||{},onHelper:()=>navigate('catalog-helper'),onGraph:async serviceId=>{focusType='service';focusId=serviceId;await navigate('mapping');},onSaved:async()=>{const entries=await Promise.all(Object.keys(resources).map(async r=>[r,await all(r)]));if(mine===epoch)catalog=Object.fromEntries(entries);}});return true;}if(next==='catalog-helper'){const mine=epoch;main.innerHTML=head('基础资源配置','维护独立或历史资源；新服务使用整项录入')+'<button class="btn" data-route="catalog">← 资源录入</button><div id="catalog-entry"></div>';catalogController=GatewayCatalogEntry.mount(document.querySelector('#catalog-entry'),{api:A,escape:e,session,initial:id||{},onService:serviceId=>navigate('catalog',{id:serviceId}),onSaved:async()=>{const entries=await Promise.all(Object.keys(resources).map(async r=>[r,await all(r)]));if(mine===epoch)catalog=Object.fromEntries(entries);}});return true;}if(next==='manual-import'){main.innerHTML=head('手动监控数据导入','离线演示：上传人工快照，明确采样时间与来源')+'<div id="manual-import-root"></div>';manualImportController=GatewayManualImport.mount(document.querySelector('#manual-import-root'),{api:A,escape:e,canWrite:canWrite()});return true;}if(next==='monitoring'){main.innerHTML=head('监控数据管理','按集群维护监控来源、配置与 CSV 快照')+'<div id="monitoring-root"></div>';monitorController=GatewayMonitoring.mount(document.querySelector('#monitoring-root'),{api:A,escape:e,canWrite:canWrite(),onCatalogChange:async()=>{const entries=await Promise.all(Object.keys(resources).map(async r=>[r,await all(r)]));catalog=Object.fromEntries(entries);}});return true;}if(next==='key'){if(id){const mine=epoch;try{main.innerHTML=head('正在读取一致的 Key 配置…','配置字段与授权必须处于同一版本');key=null;grants=[];const snapshot=await KeySnapshot.readKeySnapshot({request:A.request,id,isCurrent:()=>mine===epoch});if(!snapshot)return false;key=snapshot.key;grants=snapshot.grants;}catch(err){if(mine===epoch)fail(err);return false;}}else{key=null;grants=[];}main.innerHTML=keyPage();}else if(next==='overview'){ensureFocus();main.innerHTML=overview();loadOverview(epoch);loadOverviewGraph(epoch);}else main.innerHTML=keysPage();return true;}
document.addEventListener('click',async ev=>{const r=ev.target.closest('[data-route]'),f=ev.target.closest('[data-focus-type]'),t=ev.target.closest('[data-map-type]'),k=ev.target.closest('[data-key]');try{if(ev.target.closest('[data-entry-focus]')){if(focusType==='key'){await navigate('key',focusId);return;}let serviceId=focusType==='service'?focusId:null;if(focusType==='pd_group')serviceId=catalog['pd-groups'].find(x=>x.id===focusId)?.service_id;if(focusType==='endpoint')serviceId=catalog.endpoints.find(x=>x.id===focusId)?.service_id;if(['pod','node'].includes(focusType)){const members=await all('runtime-members'),matches=members.filter(x=>focusType==='node'?GatewayCatalogEntry.nodeMembers(members,focusId).some(m=>m.id===x.id)||x.node_name===focusId||x.node_uid===focusId:x.id===focusId||x.pod_uid===focusId),ids=[...new Set(matches.map(x=>x.endpoint_id))];if(ids.length>1){await navigate('catalog-helper',{collection:'runtime-members',nodeFocus:focusId});return;}serviceId=catalog.endpoints.find(x=>x.id===ids[0])?.service_id;}if(serviceId){await navigate('catalog',{id:serviceId});return;}const collection=focusType==='pod'||focusType==='node'?'runtime-members':typeResource[focusType];await navigate('catalog-helper',{collection,id:focusType==='node'?undefined:focusId,nodeFocus:focusType==='node'?focusId:undefined});return;}const modeButton=ev.target.closest('[data-mapping-mode]');if(modeButton){setMappingMode(modeButton.dataset.mappingMode);return;}if(r&&session?.access_mode)await navigate(r.dataset.route);if(f){const previousType=focusType,previousId=focusId;focusType=f.dataset.focusType;focusId=f.dataset.focusId;if(!await navigate('mapping')){focusType=previousType;focusId=previousId;}}if(t){const previousType=focusType,previousId=focusId;focusType=t.dataset.mapType;focusId=catalog[typeResource[focusType]][0]?.id||'';if(!await navigate('mapping')){focusType=previousType;focusId=previousId;}}if(k)await navigate('key',k.dataset.key);if(ev.target.closest('#new-key'))await navigate('key');if(ev.target.closest('#grant-add')){const first=document.querySelector('#grant-form .grant-card input:not(:checked):not(:disabled)');if(first){first.checked=true;first.closest('.grant-card').classList.add('selected');first.focus();}else toast('没有更多可授权模型。');}if(ev.target.closest('#refresh'))await load();}catch(err){fail(err);}});
document.addEventListener('input',ev=>{if(ev.target.id==='map-search'){mapSearch=ev.target.value;document.querySelector('#map-choices').innerHTML=mappingChoices();}if(ev.target.id==='search'){filter=ev.target.value;document.querySelector('#overview-rows').innerHTML=overviewRows();}});
document.addEventListener('change',ev=>{if(ev.target.id==='overview-team')overviewTeam=ev.target.value;if(ev.target.id==='overview-cluster')overviewCluster=ev.target.value;if(ev.target.id==='overview-intent')overviewIntent=ev.target.value;if(['overview-team','overview-cluster','overview-intent'].includes(ev.target.id))document.querySelector('#overview-rows').innerHTML=overviewRows();if(ev.target.name==='model_ids'){ev.target.closest('.grant-card').classList.toggle('selected',ev.target.checked);ev.target.closest('.grant-card').querySelector('em').textContent=ev.target.checked?'待保存授权':'待移除授权';}if(ev.target.id==='overview-focus-type'){document.querySelector('#overview-focus-id').innerHTML=focusOptions(ev.target.value,'');}if(ev.target.id==='focus-type'){const selector=document.querySelector('#focus-id');focusSelections[selector.dataset.focusKind]=selector.value;focusType=ev.target.value;selector.innerHTML=focusOptions(focusType,focusSelections[focusType]||'');selector.dataset.focusKind=focusType;}});
document.addEventListener('submit',async ev=>{
 if(ev.target.id.startsWith('service-entry-')||ev.target.id.startsWith('manual-import-')||ev.target.id.startsWith('monitor-')||ev.target.id.startsWith('catalog-'))return;
 ev.preventDefault();const form=ev.target,button=form.querySelector('button[type="submit"],button:not([type])');if(button)button.disabled=true;
 const mine=epoch,targetId=key?.id||null,stillCurrent=()=>route==='key'&&epoch===mine&&(key?.id||null)===targetId;
 try{
  const data=new FormData(form);
  if(form.id==='key-form'){
   const body=Object.fromEntries(data);body.enabled=form.elements.enabled.checked;delete body.confirm_disable;
   if(targetId&&form.elements.confirm_disable.checked)body.confirm_disable=true;
   body.business_id=body.business_id||null;if(targetId)body.expected_version=key.version;
   const saved=(await A.request(path('keys')+(targetId?'/'+targetId:''),{method:targetId?'PATCH':'POST',body})).data;
   toast('配置已保存；执行端未连接。');
   if(stillCurrent())key=saved;
   const freshKeys=await all('keys');
   catalog.keys=freshKeys;
   if(route==='keys')main.innerHTML=keysPage();
   if(stillCurrent())await navigate('key',saved.id);
  }
  if(form.id==='grant-form'){
   await A.request(path('keys')+'/'+targetId+'/model-grants',{method:'PUT',body:{expected_version:key.version,model_ids:data.getAll('model_ids')}});
   toast('授权已保存；执行端未连接。');
   if(stillCurrent())await navigate('key',targetId);
  }
  if(form.id==='overview-focus-form'){focusType=document.querySelector('#overview-focus-type').value;focusId=document.querySelector('#overview-focus-id').value;ensureFocus();await loadOverviewGraph(epoch);}if(form.id==='focus-form'){focusType=document.querySelector('#focus-type').value;focusId=document.querySelector('#focus-id').value;await showGraph();}
 }catch(err){if(route==='key'&&epoch===mine)fail(err);else toast('Key 操作失败：'+err.message);}
 finally{if(button)button.disabled=false;}
});
const query=new URLSearchParams(location.search);if(['catalog','monitoring','manual-import','mapping'].includes(query.get('view')))route=query.get('view');if((typeResource[query.get('focus_type')]||['node','pod'].includes(query.get('focus_type')))&&query.get('focus_id')){route='mapping';focusType=query.get('focus_type');focusId=query.get('focus_id');}load();
window.GatewayLive={graphHTML,drawGraph,get graph(){return graph;},get mappingMode(){return mappingMode;},get lastLayout(){return callflowController?.getGeometry();}};
})();
