/* Configuration relationships, projected as independent evidence-backed rows.
 * Occurrences may repeat a canonical node; they never add domain relationships. */
(function(root){'use strict';
const labels={team:'调用团队',business:'业务',key:'授权 Key',model:'模型',service:'推理服务',endpoint:'Endpoint',pod:'Pod',runtime_member:'Pod',node:'节点',cluster:'集群',pd_group:'P / D 组'};
function project(graph){
 const nodes=graph.nodes||[],edges=graph.edges||[],byId=new Map(nodes.map(n=>[n.id,n])),rows=[],used=new Set();
 const outgoing=(id,type,targetType)=>edges.map((e,index)=>({...e,index})).filter(e=>e.source===id&&e.type===type&&byId.has(e.target)&&(!targetType||byId.get(e.target).type===targetType));
 const incoming=(id,type,sourceType)=>edges.map((e,index)=>({...e,index})).filter(e=>e.target===id&&e.type===type&&byId.has(e.source)&&(!sourceType||byId.get(e.source).type===sourceType));
 const add=(kind,cells,links,note,extra=[])=>{const id='row-'+rows.length;cells.flat().filter(Boolean).forEach(n=>used.add(n.id));rows.push({id,kind,cells:cells.map(c=>c.filter(Boolean)),links:links.filter(Boolean),note,evidence:[...new Set([...links.filter(Boolean).flatMap(l=>l.evidence),...extra])]});};
 const link=(from,to,evidence,label)=>({from,to,evidence,label});
 for(const key of nodes.filter(n=>n.type==='key')){
  const businesses=incoming(key.id,'owns','business');
  let contexts=[];
  if(businesses.length)for(const bk of businesses){const b=byId.get(bk.source),owners=incoming(b.id,'owns','team');if(owners.length)for(const tb of owners)contexts.push({team:byId.get(tb.source),business:b,ownership:[tb.index,bk.index]});else contexts.push({business:b,ownership:[bk.index]});}
  else {const owners=incoming(key.id,'owns','team');contexts=owners.length?owners.map(tk=>({team:byId.get(tk.source),ownership:[tk.index]})):[{ownership:[]}];}
  const grants=outgoing(key.id,'authorizes','model');
  for(const ctx of contexts)for(const grant of grants.length?grants:[null]){
   const model=grant&&byId.get(grant.target),services=model?outgoing(model.id,'serves','service'):[];
   for(const serviceEdge of services.length?services:[null])add('authorization',[[ctx.team],[ctx.business,key],[model],[serviceEdge&&byId.get(serviceEdge.target)]],[ctx.team&&link(0,1,ctx.ownership,'归属'),grant&&link(1,2,[grant.index],'授权'),serviceEdge&&link(2,3,[serviceEdge.index],'模型服务')],grant?'配置授权范围 · 模型服务不代表实际调用目标':'尚无模型授权关系',ctx.ownership);
  }
 }
 for(const business of nodes.filter(n=>n.type==='business'))for(const binding of outgoing(business.id,'depends_on','service')){
  const owners=incoming(business.id,'owns','team'),models=incoming(binding.target,'serves','model');
  for(const owner of owners.length?owners:[null])for(const modelEdge of models.length?models:[null])add('binding',[[owner&&byId.get(owner.source)],[business],[modelEdge&&byId.get(modelEdge.source)],[byId.get(binding.target)]],[owner&&link(0,1,[owner.index],'归属'),modelEdge&&link(2,3,[modelEdge.index],'模型服务')],'业务绑定 → '+byId.get(binding.target).name+' · 此行不表示模型授权',[binding.index]);
 }
 for(const model of nodes.filter(n=>n.type==='model'&&!used.has(n.id))){const services=outgoing(model.id,'serves','service');for(const s of services.length?services:[null])add('partial',[[],[],[model],[s&&byId.get(s.target)]],[s&&link(2,3,[s.index],'模型服务')],'返回范围内无关联授权');}
 for(const n of nodes.filter(n=>['team','business','service'].includes(n.type)&&!used.has(n.id)))add('partial',[[n.type==='team'?n:null],[n.type==='business'?n:null],[],[n.type==='service'?n:null]],[],'返回范围内无完整授权链');
 const resources=new Map();
 for(const service of nodes.filter(n=>n.type==='service')){
  const endpoints=outgoing(service.id,'serves','endpoint').map(se=>{const endpoint=byId.get(se.target),pods=incoming(endpoint.id,'backs_endpoint').filter(x=>['pod','runtime_member'].includes(byId.get(x.source).type)).map(pe=>({node:byId.get(pe.source),evidence:[pe.index],hosts:outgoing(pe.source,'scheduled_on','node').map(pn=>({node:byId.get(pn.target),evidence:[pn.index],clusters:outgoing(pn.target,'runs_in','cluster').map(nc=>({node:byId.get(nc.target),evidence:[nc.index]}))}))}));return {node:endpoint,evidence:[se.index],clusters:outgoing(endpoint.id,'runs_in','cluster').map(x=>({node:byId.get(x.target),evidence:[x.index]})),pd:outgoing(endpoint.id,'member_of_pd','pd_group').map(x=>({node:byId.get(x.target),evidence:[x.index]})),pods};});
  resources.set(service.id,endpoints);
 }
 const resourceIds=new Set();for(const endpoints of resources.values())for(const ep of endpoints){resourceIds.add(ep.node.id);for(const x of [...ep.clusters,...ep.pd])resourceIds.add(x.node.id);for(const p of ep.pods){resourceIds.add(p.node.id);for(const host of p.hosts){resourceIds.add(host.node.id);host.clusters.forEach(c=>resourceIds.add(c.node.id));}}}
 return {rows,resources,byId,edges,unplaced:nodes.filter(n=>!used.has(n.id)&&!resourceIds.has(n.id))};
}
function mount(container,graph,options={}){
 const e=options.escape||((v)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))),view=project(graph),focus=options.focusType+':'+options.focusId;
 let destroyed=false,paused=false,frame=0,particleCount=0,focusBranchOpened=false,motionFrame=0,lastMotionTime=null,motionTime=0,motionStopped=false;const media=window.matchMedia('(prefers-reduced-motion: reduce)');
 const frequency=new Map();view.rows.forEach(r=>r.cells.flat().forEach(n=>frequency.set(n.id,(frequency.get(n.id)||0)+1)));
 const button=(n,extra='')=>`<button type="button" class="cf-node ${n.id===focus?'cf-focus':''}" data-cf-focus="${e(n.id)}"><span class="cf-type">${e(labels[n.type]||n.type)}</span><strong>${e(n.name)}</strong><span class="cf-meta">${e(n.environment_code||'未标注环境')} · ${n.origin==='DEMO'?'DEMO 演示证据':e(n.evidence_kind||n.origin||'配置证据')}${extra}</span></button>`;
 const reference=x=>button(x.node);
 const branches=(row)=>{const service=row.cells[3][0];if(!service)return '';const eps=view.resources.get(service.id)||[],ids=new Set();for(const ep of eps){ids.add(ep.node.id);[...ep.clusters,...ep.pd].forEach(x=>ids.add(x.node.id));ep.pods.forEach(p=>{ids.add(p.node.id);p.hosts.forEach(h=>{ids.add(h.node.id);h.clusters.forEach(c=>ids.add(c.node.id));});});}const open=ids.has(focus)&&!focusBranchOpened;if(open)focusBranchOpened=true;const epFocused=ep=>[ep.node,...ep.clusters.map(x=>x.node),...ep.pd.map(x=>x.node),...ep.pods.flatMap(p=>[p.node,...p.hosts.flatMap(h=>[h.node,...h.clusters.map(c=>c.node)])])].some(n=>n.id===focus);let endpointOpened=false;return `<details class="cf-deployment" data-cf-branch ${open?'open':''}><summary>部署资源 <span>${eps.length} 个 Endpoint · ${ids.size} 个关联资源</span></summary><div class="cf-resource-tree">${eps.length?eps.map(ep=>{const epOpen=open&&epFocused(ep)&&!endpointOpened;if(epOpen)endpointOpened=true;return `<details class="cf-endpoint" ${epOpen?'open':''}><summary>Endpoint · ${e(ep.node.name)}</summary><div class="cf-resource-body"><div class="cf-resource-label">服务 → Endpoint · serves</div>${reference(ep)}<div class="cf-resource-group"><span>Endpoint 所在集群 · runs_in</span>${ep.clusters.map(reference).join('')||'<small>无配置关系</small>'}</div>${ep.pd.length?`<div class="cf-resource-group"><span>Endpoint 所属 P / D 组 · member_of_pd</span>${ep.pd.map(reference).join('')}</div>`:''}<div class="cf-resource-group"><span>支撑该 Endpoint 的 Pod · Pod → Endpoint / backs_endpoint</span>${ep.pods.length?ep.pods.map(p=>`<div class="cf-pod">${reference(p)}${p.hosts.map(h=>`<div class="cf-resource-group"><span>Pod 调度节点 · scheduled_on</span>${reference(h)}<div class="cf-resource-group"><span>节点所在集群 · runs_in</span>${h.clusters.map(reference).join('')||'<small>无配置关系</small>'}</div></div>`).join('')}</div>`).join(''):'<small>无运行成员证据</small>'}</div></div></details>`;}).join(''):'<p class="cf-muted">返回范围内没有 Endpoint 部署关系。</p>'}</div></details>`;};
 const connector=(row,column)=>{const rel=row.links.find(l=>l.from===column&&l.to===column+1);if(!rel)return '<div class="cf-gap"><span>—</span></div>';const id=row.id+'-edge-'+column,particle=particleCount++<6;return `<div class="cf-link" data-cf-source="${row.id}-${column}" data-cf-target="${row.id}-${column+1}" data-cf-evidence="${rel.evidence.join(',')}"><span>${e(rel.label)}</span><svg class="cf-svg" viewBox="0 0 60 20" preserveAspectRatio="none" aria-label="${e(rel.label)}"><path id="${id}" d="M 0 10 L 60 10"/><path class="cf-arrow" d="M 54 6 L 60 10 L 54 14"/>${particle?`<circle r="2" cy="10" cx="${(particleCount%5)*12}" data-cf-phase="${particleCount%5}" class="cf-particle"/>`:''}</svg></div>`;};
 container.innerHTML=`<div class="callflow"><div class="cf-intro"><div><b>调用关系</b><p>调用团队 → 业务 / 授权 → 模型 → 服务</p></div><span>配置关系展示 · 非实际请求记录</span></div><div class="cf-controls"><button type="button" data-cf-fold>展开全部部署</button><button type="button" data-cf-motion aria-pressed="false">暂停关系动画</button><span>粒子仅提示配置关系，非实时流量</span></div><div class="cf-locate"><span>快速定位</span>${(graph.nodes||[]).filter(n=>['model','team'].includes(n.type)).map(n=>`<button type="button" data-cf-focus="${e(n.id)}">${e(labels[n.type])} · ${e(n.name)}</button>`).join('')}</div><div class="cf-stats">${graph.nodes?.length||0} 个原始节点 · ${graph.edges?.length||0} 条原始关系${graph.truncated?' · 结果已截断，请缩小查询范围':''} · 共享对象可在不同关系行重复出现</div><div class="cf-viewport"><div class="cf-flow"><div class="cf-columns"><span>CALLING TEAM / 调用团队</span><i></i><span>业务 / 授权</span><i></i><span>模型</span><i></i><span>服务</span></div>${view.rows.length?view.rows.map(row=>`<section class="cf-row" data-cf-row="${row.id}"><div class="cf-chain">${row.cells.map((cell,i)=>`<div class="cf-cell ${cell.length?'':'cf-missing'}" data-cf-cell="${row.id}-${i}">${cell.length?cell.map(n=>button(n,frequency.get(n.id)>1?' · 重复引用':'')).join(''):`<span>${['无团队归属证据','无业务 / 授权关系','无模型关系','无服务关系'][i]}</span>`}${i===1&&row.kind==='binding'?'<small class="cf-binding-note">服务依赖配置 · 本行无模型授权连线</small>':''}</div>${i<3?connector(row,i):''}`).join('')}</div><p class="cf-row-note">${e(row.note)}</p>${branches(row)}</section>`).join(''):'<p class="cf-muted">返回范围内没有调用授权主链。</p>'}</div></div>${view.unplaced.length?`<details class="cf-unplaced" ${view.unplaced.some(n=>n.id===focus)?'open':''}><summary>未关联主链的对象 · ${view.unplaced.length}</summary><div>${view.unplaced.map(n=>button(n)).join('')}</div></details>`:''}<details class="cf-raw"><summary>底层事实 · ${graph.nodes?.length||0} 个节点 / ${view.edges.length} 条关系</summary><p>完整保留当前返回范围；主链按证据组织，不推断实际调用。</p><div class="cf-raw-nodes">${(graph.nodes||[]).map(n=>button(n)).join('')}</div><ol>${view.edges.map(x=>`<li>${e(view.byId.get(x.source)?.name||x.source)} → <b>${e(x.type)}</b> → ${e(view.byId.get(x.target)?.name||x.target)}</li>`).join('')}</ol></details></div>`;
 function tickMotion(time){if(destroyed||motionStopped)return;if(lastMotionTime!==null)motionTime+=Math.min(80,time-lastMotionTime);lastMotionTime=time;container.querySelectorAll('.cf-particle').forEach(p=>p.setAttribute('cx',String(((motionTime/1000+Number(p.dataset.cfPhase))%5)*12)));motionFrame=requestAnimationFrame(tickMotion);}
 function syncMotion(){if(destroyed)return;const stop=paused||media.matches||document.hidden;motionStopped=stop;cancelAnimationFrame(motionFrame);lastMotionTime=null;if(!stop)motionFrame=requestAnimationFrame(tickMotion);container.querySelectorAll('.cf-svg').forEach(svg=>{if(stop)svg.pauseAnimations?.();else svg.unpauseAnimations?.();});const b=container.querySelector('[data-cf-motion]');if(b){b.disabled=media.matches;b.setAttribute('aria-pressed',String(stop));b.textContent=media.matches?'系统已减少动态效果':paused?'播放关系动画':'暂停关系动画';}}
 function getGeometry(){const base=container.getBoundingClientRect(),rects=new Map();container.querySelectorAll('[data-cf-cell]').forEach(el=>{const r=el.getBoundingClientRect();rects.set(el.dataset.cfCell,{x:r.left-base.left,y:r.top-base.top,width:r.width,height:r.height});});const routes=[...container.querySelectorAll('.cf-link')].map(el=>{const r=el.querySelector('svg').getBoundingClientRect();return {source:el.dataset.cfSource,target:el.dataset.cfTarget,points:[[r.left-base.left,r.top-base.top+r.height/2],[r.right-base.left,r.top-base.top+r.height/2]],evidence:el.dataset.cfEvidence.split(',').map(Number)};});return {rects,routes,rows:view.rows};}
 function onClick(ev){const target=ev.target.closest('[data-cf-focus]');if(target&&container.contains(target)){const id=target.dataset.cfFocus,split=id.indexOf(':');options.onFocus?.(id.slice(0,split),id.slice(split+1));return;}if(ev.target.closest('[data-cf-motion]')){paused=!paused;syncMotion();}if(ev.target.closest('[data-cf-fold]')){const list=[...container.querySelectorAll('[data-cf-branch], .cf-endpoint')],open=list.some(d=>!d.open);list.forEach(d=>d.open=open);updateFold();}}
 function updateFold(){const b=container.querySelector('[data-cf-fold]');if(b)b.textContent=[...container.querySelectorAll('[data-cf-branch], .cf-endpoint')].some(d=>!d.open)?'展开全部部署':'折叠全部部署';}
 function onResize(){if(destroyed)return;cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{if(!destroyed)container.dispatchEvent(new CustomEvent('callflow-layout'));});}
 container.addEventListener('click',onClick);container.addEventListener('toggle',updateFold,true);document.addEventListener('visibilitychange',syncMotion);media.addEventListener('change',syncMotion);const observer=new ResizeObserver(onResize);observer.observe(container);syncMotion();updateFold();
 const controller={getGeometry,destroy(){if(destroyed)return;destroyed=true;cancelAnimationFrame(frame);cancelAnimationFrame(motionFrame);observer.disconnect();container.querySelectorAll('.cf-svg').forEach(s=>s.pauseAnimations?.());container.removeEventListener('click',onClick);container.removeEventListener('toggle',updateFold,true);document.removeEventListener('visibilitychange',syncMotion);media.removeEventListener('change',syncMotion);container.innerHTML='';delete container.callflowController;}};
 container.callflowController=controller;return controller;
}
const api={project,mount,labels};if(typeof module!=='undefined')module.exports=api;else root.GatewayCallflow=api;
})(typeof window==='undefined'?globalThis:window);
