/* Cluster-scoped monitor configuration. Validation never writes; apply revalidates server-side. */
(function(root){'use strict';
const kinds={'cluster-config':'集群 / PD 配置','endpoint-metrics':'推理监控','hardware-metrics':'硬件监控'};
function mount(container,{api,escape:e,canWrite,onCatalogChange=()=>{}}){
 let clusters=[],options={providers:[]},selected='',draft=null,alive=true,busy=false,generation=0,validationGeneration=0;
 const url='/api/v1/monitoring/',current=()=>clusters.find(c=>c.id===selected),stamp=v=>v?new Date(v).toLocaleString('zh-CN',{hour12:false}):'尚未导入';
 function error(err){if(!alive)return;const box=container.querySelector('[data-monitor-error]');box.hidden=false;box.innerHTML=`<b>${e(err.message)}</b>${(err.payload?.error?.details?.rows||[]).slice(0,50).map(r=>`<p>第 ${e(r.row)} 行 · ${e(r.field)}：${e(r.message)}</p>`).join('')}`;}
 async function refresh(){const seq=++generation;const values=await Promise.all([api.request(url+'clusters'),canWrite?api.request(url+'options'):Promise.resolve({data:{providers:[]}})]);if(!alive||seq!==generation)return;clusters=values[0].data.items;options=values[1].data;if(!clusters.some(c=>c.id===selected))selected=clusters[0]?.id||'';draft=null;render();}
 const input=(field,label,value='',required=true)=>`<label>${e(label)}<input name="${field}" value="${e(value)}" ${required?'required':''}></label>`;
 function bindingForm(c){const providers=(options.providers||[]).filter(p=>p.environment_code===c.environment_code);return `<details class="monitor-binding"><summary>配置巡检身份映射</summary><p class="sub">选择服务端已配置的巡检平台，填写巡检环境与对象身份。地址及凭证由管理员在服务端维护。</p>${!providers.length?'<p>此环境尚无可选巡检平台，请管理员完成服务端配置。</p>':`<form id="monitor-binding-form"><div class="form-grid"><label>映射类型<select name="binding_kind"><option value="engine">推理 Endpoint</option><option value="hardware">硬件资源</option></select></label><label>已有映射 / 新建<select name="binding_id"><option value="">新建映射</option></select></label><label>巡检平台<select name="provider_id" required>${providers.map(p=>`<option value="${e(p.id)}">${e(p.name)}</option>`).join('')}</select></label>${input('code','映射代码')}${input('name','映射名称')}${input('environment_id','巡检环境 UUID')}<div data-engine-fields>${engineFields(c)}</div><div data-hardware-fields hidden>${hardwareFields()}</div></div><div class="form-actions"><button class="btn primary">保存身份映射</button></div></form>`}</details>`;}
 function engineFields(c){return `<label>目标 Endpoint<select name="endpoint_id" required>${(c.endpoints||[]).map(x=>`<option value="${e(x.id)}">${e(x.name)} · ${e(x.code)}</option>`).join('')}</select></label><label>引擎类型<select name="engine_type"><option>vllm</option><option>sglang</option></select></label>${input('engine_id','巡检引擎 ID')}${input('model_name','巡检模型名称')}`;}
 function hardwareFields(){return `<label>资源类型<select name="resource_type"><option value="HOST">主机 HOST</option><option value="GPU_POOL">单 GPU</option></select></label>${input('asset_id','巡检资产 UUID')}${input('host_id','巡检主机 ID')}${input('gpu_uuid','GPU UUID（仅 GPU）','',false)}`;}
 function render(){const c=current();container.innerHTML=`<div data-monitor-error class="error" role="alert" hidden></div><section class="panel"><div class="panel-head"><div><h2>集群监控来源</h2><p>逐集群选择巡检或 CSV；CSV 保留至下一次替换，按原始采样时间展示。</p></div><button class="btn" data-monitor-refresh>刷新状态</button></div><div class="monitor-layout"><aside class="monitor-clusters">${clusters.map(x=>`<button data-monitor-cluster="${e(x.id)}" class="${x.id===selected?'active':''}"><b>${e(x.name)}</b><span>${e(x.environment_code)} · ${e(x.monitoring_source==='CSV'?'CSV 快照':'巡检')}</span></button>`).join('')||'<p>尚未登记集群</p>'}</aside><div class="monitor-detail">${c?`<h2>${e(c.name)}</h2><p class="sub">${e(c.code)} · ${e(c.environment_code)} · ${e(c.region||'地域未填写')} · 版本 ${e(c.version)}</p><form id="monitor-source-form"><label>监控来源<select name="source" ${!canWrite?'disabled':''}><option value="INSPECTION" ${c.monitoring_source==='INSPECTION'?'selected':''}>巡检平台</option><option value="CSV" ${c.monitoring_source==='CSV'?'selected':''}>CSV 快照</option></select></label>${canWrite?'<button class="btn primary">保存来源</button>':''}</form><div class="monitor-snapshot"><b>${c.monitoring_source==='CSV'?'CSV 快照 · 状态未知':'已保留 CSV 快照 · 未启用'}</b><p>CSV 推理：${e(c.snapshot?.endpoint_count||0)} 个 Endpoint · 采样 ${e(stamp(c.snapshot?.endpoint_sampled_at))}</p><p>CSV 硬件：${e(c.snapshot?.hardware_count||0)} 项资源 · 采样 ${e(stamp(c.snapshot?.hardware_sampled_at))}</p><small>${c.monitoring_source==='CSV'?'上传值不是实时健康判断；未上传对象不回退巡检。':'当前使用巡检，按来源窗口老化；上述为保留的 CSV 元数据，不代表当前巡检观测。'}</small></div><details><summary>此集群的 Endpoint（${c.endpoints?.length||0}）</summary><div class="monitor-endpoints">${(c.endpoints||[]).map(x=>`<p><b>${e(x.name)}</b> · ${e(x.code)} · ${e(x.role)}<br><small>${e(x.model_name||'')} / ${e(x.service_name||'')} / ${e(x.pd_group_name||'')}</small></p>`).join('')}</div></details>${canWrite?bindingForm(c):''}`:'<p>下载配置模板并导入，即可建立新集群及 PD / Endpoint。</p>'}</div></div></section><section class="panel pad"><h2>CSV 模板与导入</h2><p class="sub">模板含示例行，请替换为自己的数据。配置导入为新增 / 更新；监控导入分别替换推理或硬件快照。空单元格表示缺失，不是零。</p><div class="monitor-templates">${Object.entries(kinds).map(([k,label])=>`<a class="btn" href="${url}templates/${k}.csv" download>${label}模板 ↓</a>`).join('')}</div>${canWrite?`<form id="monitor-import-form"><div class="form-grid"><label>导入内容<select name="kind">${Object.entries(kinds).map(([k,label])=>`<option value="${k}">${label}</option>`).join('')}</select></label><label>目标范围<select name="target"><option value="">新建集群（仅配置）</option>${clusters.map(x=>`<option value="${e(x.id)}" ${x.id===selected?'selected':''}>${e(x.name)} · ${e(x.environment_code)}</option>`).join('')}</select></label><label>CSV 文件（最大 1 MiB）<input name="file" type="file" accept=".csv,text/csv" required></label></div><div class="form-actions"><button class="btn primary">校验并预览</button></div></form><div data-import-preview aria-live="polite"></div>`:'<p>当前身份只读，管理员可导入和修改来源。</p>'}</section>`;syncBinding();}
 function bindings(kind){const c=current();return kind==='engine'?(c?.endpoints||[]).flatMap(ep=>(ep.engine_bindings||ep.bindings||(ep.engine_binding?[ep.engine_binding]:[])).map(b=>({...b,endpoint_id:ep.id}))):c?.hardware||[];}
 function syncBinding(){const f=container.querySelector('#monitor-binding-form');if(!f)return;const kind=f.elements.binding_kind.value;for(const [selector,on] of [['[data-engine-fields]',kind==='engine'],['[data-hardware-fields]',kind==='hardware']]){const box=f.querySelector(selector);box.hidden=!on;box.querySelectorAll('input,select').forEach(x=>x.disabled=!on);}f.elements.binding_id.innerHTML='<option value="">新建映射</option>'+bindings(kind).map(b=>`<option value="${e(b.id)}">${e(b.name||b.code||b.engine_id)}</option>`).join('');}
 function invalidate(){validationGeneration++;draft=null;const p=container.querySelector('[data-import-preview]');if(p)p.innerHTML='';}
 container.addEventListener('change',ev=>{if(ev.target.closest('#monitor-import-form'))invalidate();const f=ev.target.closest('#monitor-binding-form');if(!f)return;if(ev.target.name==='binding_kind')syncBinding();if(ev.target.name==='binding_id'){const b=bindings(f.elements.binding_kind.value).find(x=>x.id===ev.target.value);if(b)Object.entries(b).forEach(([k,v])=>{if(f.elements[k])f.elements[k].value=v??'';});}});
 container.addEventListener('click',async ev=>{try{if(busy)return;const b=ev.target.closest('[data-monitor-cluster]');if(b){selected=b.dataset.monitorCluster;draft=null;render();}if(ev.target.closest('[data-monitor-refresh]'))await refresh();if(ev.target.closest('[data-monitor-apply]')&&draft){busy=true;const saved=draft;await api.request(url+'imports/apply',{method:'POST',body:saved});await refresh();await onCatalogChange();container.querySelector('[data-import-preview]').textContent='导入完成，集群快照已更新。';}}catch(err){error(err);}finally{busy=false;}});
 container.addEventListener('submit',async ev=>{const f=ev.target;if(!f.id.startsWith('monitor-'))return;ev.preventDefault();ev.stopPropagation();if(busy)return;busy=true;const btn=f.querySelector('button');btn.disabled=true;try{const data=new FormData(f),c=current();if(f.id==='monitor-source-form'){await api.request(url+'clusters/'+c.id+'/source',{method:'PATCH',body:{source:data.get('source'),expected_version:c.version}});await refresh();}if(f.id==='monitor-import-form'){invalidate();const validation=validationGeneration;const file=data.get('file');if(file.size>1048576)throw new Error('CSV 文件超过 1 MiB 限制');const csv=await file.text(),kind=data.get('kind'),cluster_id=data.get('target');if(kind!=='cluster-config'&&!cluster_id)throw new Error('监控数据必须选择目标集群');const body={kind,csv,...(cluster_id?{cluster_id}:{})};const result=(await api.request(url+'imports/validate',{method:'POST',body})).data;if(!alive||validation!==validationGeneration)return;draft={...body,expected_version:result.expected_version,normalized_hash:result.normalized_hash};container.querySelector('[data-import-preview]').innerHTML=`<div class="monitor-preview"><h3>校验通过 · ${e(result.row_count)} 行</h3><p>${e(kinds[kind])} → ${e(clusters.find(x=>x.id===cluster_id)?.name||'新建集群')}</p><pre>${e(typeof result.summary==='string'?result.summary:JSON.stringify(result.summary,null,2))}</pre><button class="btn primary" data-monitor-apply>确认导入已校验内容</button></div>`;}if(f.id==='monitor-binding-form'){const kind=data.get('binding_kind'),id=data.get('binding_id'),existing=bindings(kind).find(x=>x.id===id),fields=kind==='engine'?['endpoint_id','engine_type','engine_id','model_name']:['resource_type','asset_id','host_id','gpu_uuid'];const body=Object.fromEntries(['code','name','provider_id','environment_id',...fields].map(k=>[k,data.get(k)]));Object.assign(body,{environment_code:c.environment_code,enabled:true});if(kind==='engine'){body.scope=existing?.scope||'ENDPOINT';body.runtime_member_id=existing?.runtime_member_id||null;}else body.cluster_id=c.id;if(existing)body.expected_version=existing.version;await api.request('/api/v1/catalog/'+(kind==='engine'?'engine-bindings':'hardware-bindings')+(id?'/'+id:''),{method:id?'PATCH':'POST',body});await refresh();}}catch(err){error(err);}finally{busy=false;if(btn.isConnected)btn.disabled=false;}});
 refresh().catch(error);return {destroy(){alive=false;generation++;draft=null;},refresh};
}
const api={mount,kinds};if(typeof module!=='undefined')module.exports=api;root.GatewayMonitoring=api;
})(typeof window!=='undefined'?window:globalThis);
