(function(root){'use strict';
const BASE='/api/v1/service-entry',ENV=['PRD','DR','STG','DEV'],clone=x=>JSON.parse(JSON.stringify(x));
let keyCounter=0;const formKey=prefix=>prefix+'-'+(++keyCounter);
const parent=()=>({id:'',create:false,name:'',owner:'',region:''});
const endpoint=role=>({form_key:formKey('instance'),name:'',role,cluster:parent(),namespace:'',workload_kind:'Deployment',workload_ref:'',address_ref:'',configured_nodes:[]});
const group=()=>({form_key:formKey('group'),name:'',endpoints:[endpoint('PREFILL'),endpoint('DECODE')]});
function fresh(){return {name:'',environment_code:'PRD',deployment_mode:'COMBINED',team:parent(),model:parent(),businesses:[parent()],groups:[group()],endpoints:[endpoint('COMBINED')]};}
const ref=(p,type)=>p.create?{create:{form_key:p.form_key||(p.form_key=formKey(type)),name:p.name,...(type==='business'?{owner:p.owner,critical:!!p.critical,watch_order:p.watch_order===''||p.watch_order==null?null:Number(p.watch_order)}:{}),...(type==='cluster'?{region:p.region}:{} )}}:{id:p.id};
function hydrate(s){const d=fresh(),b=(s.businesses||[]).filter(x=>x.binding_enabled===true);Object.assign(d,s.service,{model:{...parent(),id:s.service.model_id},team:{...parent(),id:b[0]?.team_id||''},businesses:b.map(x=>({...parent(),id:x.id})),groups:[],endpoints:[]});
 const ep=x=>({...clone(x),cluster:{...parent(),id:x.cluster_id},configured_nodes:clone(x.configured_nodes||[])});
 d.groups=s.groups.filter(x=>x.enabled).map(x=>({...clone(x),endpoints:s.endpoints.filter(y=>y.enabled&&y.pd_group_id===x.id).map(ep)}));d.endpoints=s.endpoints.filter(x=>x.enabled&&!x.pd_group_id).map(ep);return d;}
function bundle(d,snapshot,context){
 const original=snapshot?.endpoints||[],originalGroups=snapshot?.groups||[];
 const encode=x=>{const old=original.find(o=>o.id===x.id);if(old&&JSON.stringify(['name','role','namespace','workload_kind','workload_ref','address_ref','configured_nodes'].map(k=>old[k]??(k==='configured_nodes'?[]:'')))===JSON.stringify(['name','role','namespace','workload_kind','workload_ref','address_ref','configured_nodes'].map(k=>x[k]??(k==='configured_nodes'?[]:'')))&&x.cluster.id===old.cluster_id&&!x.cluster.create)return {id:x.id,unchanged:true};return {...(x.id?{id:x.id}:{form_key:x.form_key}),name:x.name,role:x.role,cluster_ref:ref(x.cluster,'cluster'),namespace:x.namespace,workload_kind:x.workload_kind,workload_ref:x.workload_ref,address_ref:x.address_ref,configured_nodes:x.configured_nodes.map(n=>n.trim())};};
 const groups=d.deployment_mode==='SPLIT_PD'?d.groups.map(g=>({... (g.id?{id:g.id}:{form_key:g.form_key}),name:g.name,endpoints:g.endpoints.map(encode)})):[],endpoints=d.deployment_mode==='COMBINED'?d.endpoints.map(encode):[];
 const retained=new Set([...endpoints,...groups.flatMap(x=>x.endpoints)].map(x=>x.id).filter(Boolean)),groupIds=new Set(groups.map(x=>x.id));
 return {expected_metadata_revision:context.metadata_revision,expected_versions:clone(context.expected_versions||{}),service:{name:d.name,environment_code:d.environment_code,deployment_mode:d.deployment_mode,model_ref:ref(d.model,'model')},...(d.team.create||d.team.id?{team_ref:ref(d.team,'team')}:{}),business_refs:d.businesses.filter(x=>x.create||x.id).map(x=>ref(x,'business')),remove_business_ids:(snapshot?.businesses||[]).filter(x=>x.binding_enabled===true&&!d.businesses.some(b=>b.id===x.id)).map(x=>x.id),groups,endpoints,retire_ids:{groups:originalGroups.filter(x=>x.enabled&&!groupIds.has(x.id)).map(x=>x.id),endpoints:original.filter(x=>x.enabled&&!retained.has(x.id)&&(!x.pd_group_id||groupIds.has(x.pd_group_id))).map(x=>x.id)}};
}
const csvText=(columns,rows)=>[columns,...rows.map(r=>Array.isArray(r)?r:columns.map(c=>r[c]??''))].map(r=>r.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(',')).join('\r\n');
function mount(host,{api,escape:e,session,initial={},onSaved=async()=>{},onGraph=()=>{},onHelper=()=>{}}){
 let alive=true,seq=0,listSeq=0,saving=false,ready=false,dirty=false,unknown=false,tab=initial.id?'direct':'direct',d=fresh(),snapshot=null,context={},list=[],csv='',plan=null,notice='',error=false,query='',directoryEnv=initial.environment_code||'';if(ENV.includes(initial.environment_code))d.environment_code=initial.environment_code;
 const current=n=>alive&&n===seq,$=s=>host.querySelector(s),get=p=>p.split('.').reduce((a,k)=>a?.[k],d),set=(p,v)=>{let a=d,parts=p.split('.');for(const k of parts.slice(0,-1))a=a[k];a[parts.at(-1)]=v;};
 const field=(path,label,{required=true,options=null,disabled=false}={})=>`<label><span class="se-field-label">${e(label)}</span>${options?`<select data-se-field="${path}" ${required?'required':''} ${disabled?'disabled':''}>${options.map(([v,l])=>`<option value="${e(v)}" ${String(get(path))===String(v)?'selected':''}>${e(l)}</option>`).join('')}</select>`:`<input data-se-field="${path}" value="${e(get(path)||'')}" ${required?'required':''} ${disabled?'disabled':''}>`}</label>`;
 function chooser(path,type,label){const p=get(path),opts=context.options?.[type+'s']||context.options?.[type==='business'?'businesses':type+'s']||[];return `<div class="se-parent se-parent-${type}"><div class="se-parent-head"><b>${e(label)}</b><label class="se-check"><input type="checkbox" data-se-create="${path}" ${p.create?'checked':''}>同页新建</label></div><div class="se-parent-fields ${p.create?'se-parent-creating':''}">${p.create?field(path+'.name',label+'名称')+(type==='business'?field(path+'.owner','业务负责人')+field(path+'.watch_order','关注顺序',{required:false})+`<label class="se-check"><input type="checkbox" data-se-field="${path}.critical" ${p.critical?'checked':''}>关键业务</label>`:'')+(type==='cluster'?field(path+'.region','区域',{required:false}):''):field(path+'.id','选择已有'+label,{required:type!=='team'||d.businesses.some(x=>x.create||x.id),options:[['','请选择'],...opts.filter(x=>x.enabled||p.id===x.id).map(x=>[x.id,x.name+(x.enabled?'':' · 已停用（原关联）')]) ]})}</div></div>`;}
 function instance(x,path){return `<article class="se-instance"><div class="se-instance-title"><b>${e(x.role)} · ${e(x.name||'新实例')}</b><button type="button" class="btn" data-se-remove="${path}">${x.id?'退休实例':'移除实例'}</button></div><div class="se-grid se-instance-grid">${field(path+'.name','实例名称')}${chooser(path+'.cluster','cluster','K8s 集群')}${field(path+'.namespace','K8s Namespace')}${field(path+'.workload_kind','部署方式',{options:[['','未登记'],['LWS','LWS'],['Deployment','Deployment']]})}${field(path+'.workload_ref','工作负载名称')}${field(path+'.address_ref','实例地址引用')}</div><details class="se-nodes" ${x.configured_nodes.length?'open':''}><summary>配置节点 · 未验证运行位置 · ${x.configured_nodes.length} 个</summary><div class="se-nodes-content"><p>可登记多个 Node / 部署范围；不会生成 Pod、UID 或运行观测。</p><div class="se-node-list">${x.configured_nodes.map((n,i)=>`<div class="se-node">${field(path+'.configured_nodes.'+i,'Node '+(i+1)+' 名称',{required:false})}<button class="btn" type="button" data-se-remove="${path}.configured_nodes.${i}">移除</button></div>`).join('')}</div><button class="btn" type="button" data-se-node="${path}">＋ 配置 Node</button></div></details>${x.id?`<small class="se-identity">系统身份 ${e(x.id)} · 旧配置未修改时可原样保留，修改后需补齐部署信息。</small>`:''}</article>`;}
 function direct(){return `<form id="service-entry-form" novalidate><section class="se-section se-basics"><div class="se-section-head"><h2>${snapshot?'编辑':'新建'}整项推理服务</h2>${snapshot?`<button class="btn" type="button" data-se-graph="${e(snapshot.service.id)}">查看此服务关系图 ↗</button>`:''}</div><div class="se-grid se-basics-grid">${field('name','推理服务名称')}${field('environment_code','服务所属环境',{options:[...new Set([...ENV,d.environment_code])].map(x=>[x,x==='local'?'local（本地演示）':x]),disabled:!!snapshot})}${field('deployment_mode','部署模式',{options:[['COMBINED','合并推理'],['SPLIT_PD','P / D 分离']]})}${chooser('model','model','模型')}${chooser('team','team','团队')}</div><div class="se-business-section"><div class="se-section-head"><h3>业务关联</h3><button class="btn" type="button" data-se-business>＋ 业务关联</button></div><p>维护全部当前关联；已解除的关联保留在只读历史。无业务时可不选择团队；新增业务时选择所属团队，现有业务归属保持原值。</p><div class="se-businesses">${d.businesses.map((b,i)=>`<div class="se-business-row">${chooser('businesses.'+i,'business','业务')}<button class="btn" type="button" data-se-remove="businesses.${i}">解除此业务关联</button></div>`).join('')}</div></div></section><section class="se-section se-deployment"><h2>部署实例</h2><p>登记配置不会部署工作负载。删除已有组或实例会退休配置并保留全部运行历史。</p>${d.deployment_mode==='COMBINED'?d.endpoints.map((x,i)=>instance(x,'endpoints.'+i)).join('')+`<button class="btn" type="button" data-se-add="endpoints" data-role="COMBINED">＋ 合并实例</button>`:d.groups.map((g,i)=>`<section class="se-group"><div class="se-section-head se-group-head">${field('groups.'+i+'.name','P/D 组名称')}<button class="btn" type="button" data-se-remove="groups.${i}">${g.id?'退休组':'移除组'}</button></div>${g.endpoints.map((x,j)=>instance(x,`groups.${i}.endpoints.${j}`)).join('')}<div class="se-actions">${['PREFILL','DECODE','ROUTER'].map(role=>`<button class="btn" type="button" data-se-add="groups.${i}.endpoints" data-role="${role}">＋ ${role==='ROUTER'?'可选 Router':role+' 实例'}</button>`).join('')}</div></section>`).join('')+`<button class="btn" type="button" data-se-group>＋ P/D 组</button>`}</section>${snapshot?historyHTML():''}<section class="se-save"><span>${unknown?'结果未知，请先核对目录':dirty?'有未保存的修改':snapshot?'已保存 · '+e(snapshot.service.id):'UUID 与稳定代码由服务器生成'}</span><button class="btn primary" type="submit" ${!ready||saving||unknown||!session?.can_write?'disabled':''}>${saving?'正在保存…':'保存整项服务'}</button></section><p class="se-key-note">API Key 引用与授权在 API Key 管理中维护；整项保存保留现有 Key 与授权。</p></form>`;}
 function historyHTML(){const groups=snapshot.groups.filter(x=>!x.enabled),eps=snapshot.endpoints.filter(x=>!x.enabled),inactiveBusinesses=(snapshot.businesses||[]).filter(x=>x.binding_enabled!==true);return `<details class="se-section se-history"><summary>只读历史与系统身份 · ${groups.length} 个退休组 / ${eps.length} 个退休实例 / ${inactiveBusinesses.length} 个已解除业务关联</summary><pre>${e(JSON.stringify({service_id:snapshot.service.id,code:snapshot.service.code,version:snapshot.service.version,retired_groups:groups,retired_endpoints:eps,inactive_business_bindings:inactiveBusinesses,runtime_members:snapshot.runtime_members,engine_bindings:snapshot.engine_bindings},null,2))}</pre></details>`;}
 function directory(){const rows=list.filter(x=>(x.name+' '+x.environment_code).toLowerCase().includes(query.toLowerCase()));return `<div class="se-directory"><div class="se-actions se-directory-toolbar"><label>目录环境<select data-se-directory-env><option value="">全部环境</option>${[...new Set([...ENV,...list.map(x=>x.environment_code),directoryEnv])].filter(Boolean).map(x=>`<option value="${e(x)}" ${directoryEnv===x?'selected':''}>${e(x==='local'?'local（本地演示）':x)}</option>`).join('')}</select></label><input data-se-search aria-label="搜索已录入服务" placeholder="搜索已录入服务" value="${e(query)}"><button class="btn" data-se-directory-refresh>刷新目录</button><button class="btn" data-se-new>＋ 新服务</button></div><div class="se-table"><table class="se-directory-table"><thead><tr><th>推理服务</th><th>环境</th><th>模式 / 状态</th><th>操作</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${e(x.name)}<small>${e(x.id)}</small></td><td>${e(x.environment_code)}</td><td>${e(x.deployment_mode)} · ${x.enabled?'启用':'已退休'}</td><td><div class="se-directory-actions"><button class="btn" data-se-edit="${e(x.id)}">整项编辑 / 历史</button> <button class="btn se-quiet" data-se-graph="${e(x.id)}">关系图 ↗</button> <a class="btn se-quiet" href="${BASE}/services/${e(x.id)}/export" download>完整 JSON</a> <a class="btn se-quiet" href="${BASE}/services/${e(x.id)}/export?format=csv" download>单业务配置复制 CSV</a></div></td></tr>`).join('')||'<tr class="se-empty-row"><td colspan="4">暂无已录入服务</td></tr>'}</tbody></table></div><p>配置复制 CSV 仅支持单业务；多业务使用完整 JSON 查看并整项编辑。复制模板不含观测，不用于覆盖已有服务。</p></div>`;}
 function batch(){return `<section class="se-section se-batch"><div class="se-section-head"><h2>全服务批量创建</h2><a class="btn" href="${BASE}/templates/services.csv" download>下载模板与显式示例</a></div><p>一行一实例，同服务别名聚合整项。后端严格解析与校验，应用时全批一次事务；已有服务请从目录编辑。</p><label class="se-upload">上传 UTF-8 CSV<input type="file" data-se-file accept=".csv,text/csv"></label><label>或粘贴 CSV<textarea data-se-csv rows="8">${e(csv)}</textarea></label><div class="se-actions se-batch-actions"><button class="btn" data-se-validate ${saving||unknown||!csv?'disabled':''}>${saving?'处理中…':'校验全批'}</button><button class="btn primary" data-se-apply ${saving||unknown||!plan?.valid?'disabled':''}>应用全批</button></div>${plan?`<div class="se-preview"><h3>${plan.valid?'校验通过':'请修正后重新校验'} · ${plan.service_count||0} 项服务 / ${plan.endpoint_count||0} 个实例</h3>${(plan.errors||[]).map(x=>`<p class="se-error">第 ${e(x.row)} 行 · ${e(x.column)} · ${e(x.message)}</p>`).join('')}<pre>${e(JSON.stringify(plan.services||[],null,2))}</pre>${plan.columns&&plan.rows?`<details><summary>逐行修正（保存修正后必须重新校验）</summary><div class="se-table"><table><thead><tr>${plan.columns.map(c=>`<th>${e(c)}</th>`).join('')}</tr></thead><tbody>${plan.rows.map((r,i)=>`<tr>${plan.columns.map((c,j)=>`<td><input data-se-cell="${i}:${j}" value="${e(Array.isArray(r)?r[j]:r[c]??'')}"></td>`).join('')}</tr>`).join('')}</tbody></table></div></details>`:''}</div>`:''}</section>`;}
 function render(){if(!alive)return;host.innerHTML=`<div class="service-entry"><div class="se-tabs" role="tablist">${[['direct','直接录入'],['batch','批量导入'],['directory','已录入服务目录']].map(([v,l])=>`<button class="btn ${tab===v?'primary':''}" data-se-tab="${v}" aria-selected="${tab===v}">${l}</button>`).join('')}<button class="btn se-helper" data-se-helper>基础资源配置 ↗</button></div><div class="se-notice ${error?'se-error':''}" role="status">${e(notice||(!ready?'正在读取一致目录…':''))}</div><fieldset ${saving||!ready?'disabled':''}>${tab==='direct'?direct():tab==='batch'?batch():directory()}</fieldset></div>`;}
 const status=(text,bad=false)=>{notice=text;error=bad;render();};
 function confirmLeave(){if(saving){status('正在提交，请等待完成后再离开。',true);return false;}return !dirty||root.confirm('此页有未保存的修改。确定放弃并离开吗？');}
 async function loadOptions(env){const mine=++seq;ready=false;render();try{const v=await api.request(BASE+'/options?environment_code='+encodeURIComponent(env));if(!current(mine))return;context=v.data;ready=true;render();}catch(err){if(current(mine))status(err.message,true);}}
 async function loadList(){
  const mine=++listSeq,scope=seq,env=directoryEnv,isCurrent=()=>current(scope)&&mine===listSeq;
  let rows=[],cursor='';
  try{for(let i=0;i<100;i++){
   if(!isCurrent())return null;
   const v=await api.request(BASE+'/services?limit=100'+(env?'&environment_code='+encodeURIComponent(env):'')+(cursor?'&cursor='+encodeURIComponent(cursor):''));
   if(!isCurrent())return null;
   rows.push(...v.data.items);cursor=v.data.next_cursor;
   if(!cursor){list=rows;return {isCurrent};}
  }throw Error('目录超过加载上限，请缩小范围。');}
  catch(err){return isCurrent()?{isCurrent,error:err}:null;}
 }
 async function edit(id){if(!confirmLeave())return;const mine=++seq;ready=false;render();try{const v=await api.request(BASE+'/services/'+id);if(!current(mine))return;snapshot=v.data;context=v.data;d=hydrate(snapshot);dirty=false;unknown=false;tab='direct';ready=true;notice='编辑保留全部历史身份、额外业务关联与 Key 授权。';render();}catch(err){if(current(mine))status(err.message,true);}}
 async function save(){if(!ready||saving||unknown)return;saving=true;render();const mine=seq;try{const body=bundle(d,snapshot,context),v=await api.request(BASE+'/services'+(snapshot?'/'+snapshot.service.id:''),{method:snapshot?'PUT':'POST',body});if(!current(mine))return;snapshot=v.data;context=v.data;d=hydrate(snapshot);dirty=false;unknown=false;notice='保存成功 · '+snapshot.service.id;try{const loaded=await loadList();if(!loaded?.isCurrent())return;if(loaded.error)throw loaded.error;await onSaved(snapshot);}catch(err){notice='保存成功，目录刷新失败 · '+snapshot.service.id+'。请核对该 UUID，不要重复创建。';}error=false;}catch(err){if(current(mine)){error=true;unknown=!err.payload;notice=unknown?'提交结果未知。请先在已录入服务目录核对，不能自动重发。':(err.payload?.error?.code==='VERSION_CONFLICT'?'版本冲突，草稿保留。请核对目录后重新读取。':err.message)+(err.payload?.error?.details?' · '+JSON.stringify(err.payload.error.details):'');}}finally{if(current(mine)){saving=false;render();}}}
 async function importAction(apply){if(saving||!csv||unknown||apply&&!plan?.valid)return;saving=true;render();const mine=seq,submitted=csv;try{const v=await api.request(BASE+'/imports/'+(apply?'apply':'validate'),{method:'POST',body:apply?{csv:submitted,sha256:plan.sha256,expected_metadata_revision:plan.metadata_revision}:{csv:submitted}});if(!current(mine))return;if(apply){dirty=false;plan=null;csv='';notice='全批保存成功 · '+v.data.service_count+' 项服务';try{const loaded=await loadList();if(!loaded?.isCurrent())return;if(loaded.error)throw loaded.error;await onSaved();}catch{notice+='，目录刷新失败，请核对目录后继续。';}}else{plan=v.data;notice=plan.valid?'校验通过，可以应用全批。':'校验未通过，CSV 草稿保留。';}error=false;}catch(err){if(current(mine)){unknown=apply&&!err.payload;notice=unknown?'应用结果未知，请核对目录，不要重复提交。':err.message;error=true;if(apply)plan=null;}}finally{if(current(mine)){saving=false;render();}}}
 const input=ev=>{if(saving||!ready)return;const el=ev.target;if(el.dataset.seField&&el.dataset.seField!=='environment_code'){set(el.dataset.seField,el.type==='checkbox'?el.checked:el.value);dirty=true;}if(el.hasAttribute('data-se-csv')){csv=el.value;plan=null;dirty=true;const validate=$('[data-se-validate]'),apply=$('[data-se-apply]');if(validate)validate.disabled=saving||unknown||!csv;if(apply)apply.disabled=true;const preview=$('.se-preview');if(preview)preview.remove();}if(el.hasAttribute('data-se-cell')){const [i,j]=el.dataset.seCell.split(':').map(Number);const r=plan.rows[i];if(Array.isArray(r))r[j]=el.value;else r[plan.columns[j]]=el.value;csv=csvText(plan.columns,plan.rows);plan.valid=false;dirty=true;const apply=$('[data-se-apply]');if(apply)apply.disabled=true;const textarea=$('[data-se-csv]');if(textarea)textarea.value=csv;}if(el.hasAttribute('data-se-search')){query=el.value;const pos=el.selectionStart;render();const next=$('[data-se-search]');next.focus();next.setSelectionRange(pos,pos);}};
 const change=async ev=>{const el=ev.target;if(saving||!ready)return;if(el.hasAttribute('data-se-directory-env')){directoryEnv=el.value;list=[];status('正在读取所选环境的服务目录…');const loaded=await loadList();if(loaded?.isCurrent())status(loaded.error?loaded.error.message:'目录已刷新。',!!loaded.error);return;}if(el.dataset.seCreate){get(el.dataset.seCreate).create=el.checked;dirty=true;render();}if(el.dataset.seField==='deployment_mode'){if(d.deployment_mode==='SPLIT_PD'&&!d.groups.length)d.groups=[group()];if(d.deployment_mode==='COMBINED'&&!d.endpoints.length)d.endpoints=[endpoint('COMBINED')];dirty=true;render();}if(el.dataset.seField==='environment_code'){const chosen=el.value;if(dirty&&!root.confirm('切换环境会清空已有资源选择。继续吗？')){render();return;}d.environment_code=chosen;d.team=parent();d.model=parent();d.businesses=[parent()];for(const x of [...d.endpoints,...d.groups.flatMap(g=>g.endpoints)])x.cluster=parent();dirty=true;await loadOptions(chosen);}if(el.hasAttribute('data-se-file')&&el.files[0]){if(el.files[0].size>2*1024*1024){status('CSV 不能超过 2 MiB。',true);return;}const mine=seq;try{const text=new TextDecoder('utf-8',{fatal:true}).decode(await el.files[0].arrayBuffer());if(!current(mine))return;csv=text;plan=null;dirty=true;render();}catch{if(current(mine))status('文件不是有效 UTF-8，草稿保留。',true);}}};
 const click=async ev=>{const b=ev.target.closest('button');if(!b||saving||!ready)return;try{if(b.dataset.seTab){if(!confirmLeave())return;listSeq++;tab=b.dataset.seTab;render();if(tab==='directory'){const loaded=await loadList();if(!loaded?.isCurrent())return;status(loaded.error?loaded.error.message:'目录已读取。',!!loaded.error);}}if(b.hasAttribute('data-se-helper')&&confirmLeave())onHelper();if(b.dataset.seEdit)await edit(b.dataset.seEdit);if(b.dataset.seGraph&&confirmLeave())onGraph(b.dataset.seGraph);if(b.hasAttribute('data-se-new')){if(!confirmLeave())return;snapshot=null;unknown=false;d=fresh();if(ENV.includes(initial.environment_code))d.environment_code=initial.environment_code;dirty=false;tab='direct';await loadOptions(d.environment_code);}if(b.dataset.seRemove){const parts=b.dataset.seRemove.split('.'),i=Number(parts.pop());get(parts.join('.')).splice(i,1);dirty=true;render();}if(b.dataset.seNode){get(b.dataset.seNode).configured_nodes.push('');dirty=true;render();}if(b.dataset.seAdd){get(b.dataset.seAdd).push(endpoint(b.dataset.role));dirty=true;render();}if(b.hasAttribute('data-se-group')){d.groups.push(group());dirty=true;render();}if(b.hasAttribute('data-se-business')){d.businesses.push(parent());dirty=true;render();}if(b.hasAttribute('data-se-directory-refresh')){const loaded=await loadList();if(!loaded?.isCurrent())return;status(loaded.error?loaded.error.message:'目录已刷新。结果未知时请核对服务名称与系统身份。',!!loaded.error);}if(b.hasAttribute('data-se-validate'))await importAction(false);if(b.hasAttribute('data-se-apply'))await importAction(true);}catch(err){status(err.message,true);}};
 const submit=ev=>{if(ev.target.id==='service-entry-form'){ev.preventDefault();ev.stopPropagation();save();}},unload=ev=>{if(dirty||saving){ev.preventDefault();ev.returnValue='';}};
 host.addEventListener('input',input);host.addEventListener('change',change);host.addEventListener('click',click);host.addEventListener('submit',submit);root.addEventListener?.('beforeunload',unload);render();if(initial.id)edit(initial.id);else loadOptions(d.environment_code);
 return {confirmLeave,destroy(){alive=false;seq++;listSeq++;host.removeEventListener('input',input);host.removeEventListener('change',change);host.removeEventListener('click',click);host.removeEventListener('submit',submit);root.removeEventListener?.('beforeunload',unload);},getState:()=>({dirty,saving,unknown,ready,tab,snapshot,draft:clone(d),csv})};
}
const API={mount,fresh,hydrate,bundle,csvText};if(typeof module!=='undefined')module.exports=API;root.GatewayServiceEntry=API;
})(typeof window!=='undefined'?window:globalThis);
