# Generated by Django 5.2.17 on 2026-09-26 02:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.CharField(max_length=150)),
                ('action', models.CharField(max_length=64)),
                ('entity_id', models.CharField(max_length=64)),
                ('environment_code', models.CharField(max_length=80)),
                ('changes', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=240)),
                ('environment_code', models.CharField(max_length=80)),
                ('enabled', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('origin', models.CharField(default='CONFIGURED', editable=False, max_length=16)),
                ('owner', models.CharField(max_length=160)),
                ('critical', models.BooleanField(default=False)),
                ('watch_order', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['code', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=240)),
                ('environment_code', models.CharField(max_length=80)),
                ('enabled', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('origin', models.CharField(default='CONFIGURED', editable=False, max_length=16)),
                ('role', models.CharField(choices=[('ROUTER', 'ROUTER'), ('PREFILL', 'PREFILL'), ('DECODE', 'DECODE'), ('COMBINED', 'COMBINED')], max_length=16)),
                ('address_ref', models.CharField(blank=True, max_length=160)),
            ],
            options={
                'ordering': ['code', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EngineBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=240)),
                ('environment_code', models.CharField(max_length=80)),
                ('enabled', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('origin', models.CharField(default='CONFIGURED', editable=False, max_length=16)),
                ('environment_id', models.UUIDField()),
                ('engine_id', models.CharField(max_length=160)),
                ('engine_type', models.CharField(choices=[('vllm', 'vllm'), ('sglang', 'sglang')], max_length=16)),
                ('model_name', models.CharField(max_length=240)),
                ('scope', models.CharField(choices=[('ENDPOINT', 'ENDPOINT'), ('POD', 'POD')], max_length=16)),
                ('binding_version', models.PositiveIntegerField(default=1, editable=False)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='control.endpoint')),
            ],
            options={
                'ordering': ['code', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InferenceService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=240)),
                ('environment_code', models.CharField(max_length=80)),
                ('enabled', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('origin', models.CharField(default='CONFIGURED', editable=False, max_length=16)),
                ('deployment_mode', models.CharField(choices=[('COMBINED', 'COMBINED'), ('SPLIT_PD', 'SPLIT_PD')], max_length=16)),
            ],
            options={
                'ordering': ['code', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KubernetesCluster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=240)),
                ('environment_code', models.CharField(max_length=80)),
                ('enabled', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('origin', models.CharField(default='CONFIGURED', editable=False, max_length=16)),
                ('region', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['code', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=240)),
                ('environment_code', models.CharField(max_length=80)),
                ('enabled', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('origin', models.CharField(default='CONFIGURED', editable=False, max_length=16)),
            ],
            options={
                'ordering': ['code', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProviderInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=240)),
                ('environment_code', models.CharField(max_length=80)),
                ('enabled', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('origin', models.CharField(default='CONFIGURED', editable=False, max_length=16)),
                ('base_url_ref', models.URLField()),
                ('credential_ref', models.CharField(blank=True, max_length=120)),
                ('source_allowlist', models.JSONField(default=list)),
                ('plugin_versions', models.JSONField(default=list)),
                ('origin_verified', models.BooleanField(default=False)),
                ('capabilities', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['code', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.PositiveIntegerField(default=1, primary_key=True, serialize=False)),
                ('metadata', models.PositiveBigIntegerField(default=0)),
                ('telemetry', models.PositiveBigIntegerField(default=0)),
                ('view', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=240)),
                ('environment_code', models.CharField(max_length=80)),
                ('enabled', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('origin', models.CharField(default='CONFIGURED', editable=False, max_length=16)),
            ],
            options={
                'ordering': ['code', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkerLease',
            fields=[
                ('id', models.PositiveIntegerField(default=1, primary_key=True, serialize=False)),
                ('owner', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ApiKeyRef',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=240)),
                ('environment_code', models.CharField(max_length=80)),
                ('enabled', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('origin', models.CharField(default='CONFIGURED', editable=False, max_length=16)),
                ('external_key_ref', models.CharField(max_length=160, unique=True)),
                ('masked_label', models.CharField(max_length=80)),
                ('desired_status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('SUSPENDED', 'SUSPENDED')], default='ACTIVE', max_length=16)),
                ('effective_status', models.CharField(default='NOT_CONNECTED', editable=False, max_length=24)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='control.business')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='control.team')),
            ],
            options={
                'ordering': ['code', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PollState',
            fields=[
                ('binding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='control.enginebinding')),
                ('last_attempt_at', models.DateTimeField(null=True)),
                ('last_success_at', models.DateTimeField(null=True)),
                ('next_due', models.DateTimeField(null=True)),
                ('error', models.CharField(blank=True, max_length=80)),
                ('failures', models.PositiveIntegerField(default=0)),
                ('paused', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ImportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.CharField(max_length=120)),
                ('legacy_id', models.CharField(max_length=160)),
                ('entity_id', models.UUIDField()),
                ('source_hash', models.CharField(max_length=64)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('namespace', 'legacy_id'), name='unique_import_identity')],
            },
        ),
        migrations.AddField(
            model_name='endpoint',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='control.inferenceservice'),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='control.kubernetescluster'),
        ),
        migrations.AddField(
            model_name='inferenceservice',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='control.model'),
        ),
        migrations.CreateModel(
            name='PDGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=240)),
                ('environment_code', models.CharField(max_length=80)),
                ('enabled', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('origin', models.CharField(default='CONFIGURED', editable=False, max_length=16)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='control.inferenceservice')),
            ],
            options={
                'ordering': ['code', 'id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='endpoint',
            name='pd_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='control.pdgroup'),
        ),
        migrations.AddField(
            model_name='enginebinding',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='control.providerinstance'),
        ),
        migrations.CreateModel(
            name='RuntimeMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=240)),
                ('environment_code', models.CharField(max_length=80)),
                ('enabled', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('origin', models.CharField(default='CONFIGURED', editable=False, max_length=16)),
                ('namespace', models.CharField(max_length=120)),
                ('workload_ref', models.CharField(blank=True, max_length=160)),
                ('pod_uid', models.CharField(blank=True, max_length=120, null=True)),
                ('pod_name', models.CharField(blank=True, max_length=160)),
                ('node_uid', models.CharField(blank=True, max_length=120, null=True)),
                ('node_name', models.CharField(blank=True, max_length=160)),
                ('observed_at', models.DateTimeField(blank=True, null=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='control.kubernetescluster')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='control.endpoint')),
            ],
            options={
                'ordering': ['code', 'id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='enginebinding',
            name='runtime_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='control.runtimemember'),
        ),
        migrations.AddField(
            model_name='business',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='control.team'),
        ),
        migrations.CreateModel(
            name='TelemetrySnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('binding_version', models.PositiveIntegerField()),
                ('provider_snapshot_id', models.CharField(max_length=240)),
                ('source_end', models.DateTimeField()),
                ('payload', models.JSONField()),
                ('content_hash', models.CharField(max_length=64)),
                ('json_bytes', models.PositiveIntegerField()),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('binding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='control.enginebinding')),
            ],
        ),
        migrations.CreateModel(
            name='AccessScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment_code', models.CharField(max_length=80)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'environment_code'), name='unique_user_scope')],
            },
        ),
        migrations.CreateModel(
            name='BusinessServiceBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('evidence_kind', models.CharField(default='CONFIGURED', editable=False, max_length=16)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='control.business')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='control.inferenceservice')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('business', 'service'), name='unique_business_service')],
            },
        ),
        migrations.CreateModel(
            name='KeyModelGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='control.apikeyref')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='control.model')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('key', 'model'), name='unique_key_model')],
            },
        ),
        migrations.AddConstraint(
            model_name='runtimemember',
            constraint=models.UniqueConstraint(condition=models.Q(('pod_uid__isnull', False)), fields=('endpoint', 'cluster', 'pod_uid'), name='unique_runtime_uid'),
        ),
        migrations.AddConstraint(
            model_name='enginebinding',
            constraint=models.UniqueConstraint(condition=models.Q(('enabled', True)), fields=('provider', 'environment_id', 'engine_id', 'engine_type', 'model_name'), name='unique_engine_identity'),
        ),
        migrations.AddConstraint(
            model_name='business',
            constraint=models.UniqueConstraint(condition=models.Q(('critical', True), ('enabled', True)), fields=('watch_order',), name='unique_active_watch_order'),
        ),
        migrations.AddIndex(
            model_name='telemetrysnapshot',
            index=models.Index(fields=['binding', 'binding_version', 'source_end'], name='control_tel_binding_04a6eb_idx'),
        ),
        migrations.AddConstraint(
            model_name='telemetrysnapshot',
            constraint=models.UniqueConstraint(fields=('binding', 'binding_version', 'provider_snapshot_id'), name='unique_source_snapshot'),
        ),
    ]
