# Generated by Django 5.2.17 on 2026-09-26 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerinstance',
            name='capabilities',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='providerinstance',
            name='plugin_versions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='providerinstance',
            name='source_allowlist',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
