# Generated by Django 5.2.17 on 2026-09-26 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_alter_providerinstance_capabilities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerlease',
            name='rate_window',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='workerlease',
            name='request_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
