# Generated by Django 5.2.17 on 2026-09-26 09:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_workerlease_rate_window_workerlease_request_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=240)),
                ('environment_code', models.CharField(max_length=80)),
                ('enabled', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('origin', models.CharField(default='CONFIGURED', editable=False, max_length=16)),
                ('environment_id', models.UUIDField()),
                ('resource_type', models.CharField(choices=[('GPU_POOL', 'GPU_POOL'), ('HOST', 'HOST')], max_length=8)),
                ('asset_id', models.UUIDField()),
                ('host_id', models.CharField(max_length=192)),
                ('gpu_uuid', models.CharField(blank=True, max_length=192)),
                ('binding_version', models.PositiveIntegerField(default=1, editable=False)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='control.providerinstance')),
            ],
            options={
                'ordering': ['code', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HardwareObservation',
            fields=[
                ('binding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='control.hardwarebinding')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('last_attempt_at', models.DateTimeField(null=True)),
                ('last_success_at', models.DateTimeField(null=True)),
                ('next_due', models.DateTimeField(null=True)),
                ('error', models.CharField(blank=True, max_length=80)),
                ('failures', models.PositiveIntegerField(default=0)),
                ('paused', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddConstraint(
            model_name='hardwarebinding',
            constraint=models.UniqueConstraint(condition=models.Q(('enabled', True)), fields=('provider', 'environment_id', 'asset_id'), name='unique_hardware_identity'),
        ),
    ]
