# Generated by Django 5.2.17 on 2026-09-27 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_hardware_observation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterCsvSnapshot',
            fields=[
                ('cluster', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='control.kubernetescluster')),
                ('endpoint_payload', models.JSONField(default=list)),
                ('hardware_payload', models.JSONField(default=list)),
                ('endpoint_hash', models.CharField(blank=True, max_length=64)),
                ('hardware_hash', models.CharField(blank=True, max_length=64)),
                ('config_hash', models.CharField(blank=True, max_length=64)),
                ('endpoint_sampled_at', models.DateTimeField(null=True)),
                ('hardware_sampled_at', models.DateTimeField(null=True)),
                ('endpoint_imported_at', models.DateTimeField(null=True)),
                ('hardware_imported_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='hardwarebinding',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='control.kubernetescluster'),
        ),
        migrations.AddField(
            model_name='kubernetescluster',
            name='monitoring_source',
            field=models.CharField(choices=[('INSPECTION', 'INSPECTION'), ('CSV', 'CSV')], default='INSPECTION', editable=False, max_length=16),
        ),
        migrations.AddField(
            model_name='kubernetescluster',
            name='source_generation',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
    ]
