const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {mount,buildTemplate}=require('../manual-import.js');
const escaped=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
const cluster=(id='c1',source='CSV')=>({id,code:id+'-code',name:id+'集群',environment_code:'demo',version:4,monitoring_source:source,endpoints:[{code:id+'-prefill'},{code:id+'-decode'}],snapshot:{endpoint_count:0,hardware_count:0}});
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b});return {promise,resolve,reject};};
class Container{
 constructor(){this.handlers={};this.writes=0;this.html='';this.controls=[];}
 set innerHTML(html){this.html=html;this.writes++;this.controls=[...html.matchAll(/<(button|input|select)\b([^>]*)>/g)].map(([,tag,attr])=>({tag,dataset:{permanentDisabled:attr.match(/data-permanent-disabled="([^"]*)"/)?.[1]},disabled:/\bdisabled\b/.test(attr)}));}
 get innerHTML(){return this.html;}
 querySelectorAll(){return this.controls;}
 querySelector(selector){if(selector==='.manual-preview'&&this.html.includes('class="manual-preview"'))return {remove:()=>{this.html=this.html.replace(/<section class="manual-preview">[\s\S]*?<\/section>/,'');this.writes++;}};if(selector==='.manual-status')return {set textContent(v){},get textContent(){return '';}};return null;}
 setAttribute(name,v){this[name]=v;}
 addEventListener(name,f){this.handlers[name]=f;}
 removeEventListener(name,f){if(this.handlers[name]===f)delete this.handlers[name];}
 async click(action){return this.handlers.click?.({target:{closest:()=>({dataset:{manualAction:action}})}});}
 change(name,value){this.handlers.change?.({target:{name,value,closest:()=>({id:'manual-import-form'})}});}
 async upload(csv='a,b\nx,y',options={}){return this.handlers.submit?.({target:{id:'manual-import-form',elements:{file:{files:[{size:options.size??csv.length,text:options.text||(()=>Promise.resolve(csv))}]}}},preventDefault(){},stopPropagation(){}});}
}
function harness(overrides={}){const container=new Container(),calls=[],downloads=[];let items=overrides.items||[cluster(),cluster('c2')];const api={request:async(url,opts)=>{calls.push({url,opts});if(overrides.request){const value=await overrides.request(url,opts);if(value!==undefined)return value;}if(url.endsWith('clusters'))return {data:{items}};const body=opts?.body,c=items.find(c=>c.id===body?.cluster_id);if(url.endsWith('validate')||url.endsWith('apply')){if(c.monitoring_source!=='CSV')throw new Error('SOURCE_CONFLICT');if(url.endsWith('validate'))return {data:{row_count:1,summary:{sampled_at:'2026-09-01T08:00:00Z'},expected_version:c.version,normalized_hash:'server-hash'}};if(body.expected_version!==c.version||body.normalized_hash!=='server-hash')throw new Error('VERSION_CONFLICT');const updated={...c,version:c.version+1,snapshot:{...c.snapshot,[body.kind==='hardware-metrics'?'hardware_count':'endpoint_count']:1}};items=items.map(x=>x.id===c.id?updated:x);return {data:{changed:true,cluster:updated}};}if(url.endsWith('/source')){const id=url.split('/').at(-2),c=items.find(c=>c.id===id);if(body.expected_version!==c.version)throw new Error('VERSION_CONFLICT');const updated={...c,monitoring_source:body.source,version:c.version+1};items=items.map(x=>x.id===id?updated:x);return {data:updated};}throw new Error('Unexpected '+url);}};const controller=mount(container,{api,escape:escaped,canWrite:overrides.canWrite!==false,fetchTemplate:overrides.fetchTemplate||(()=>Promise.resolve('endpoint_code,sampled_at,request_rate\nexample,sample,123')),download:(text,filename)=>downloads.push({text,filename})});return {container,calls,downloads,controller,setItems:next=>items=next};}

test('templates use authoritative headers and actual endpoint codes, keep all observation cells blank',()=>{
 const c=cluster();c.endpoints=[{code:'a,"b'},{code:'actual-decode'}];const header=fs.readFileSync(path.resolve(__dirname,'../../../templates/endpoint-metrics.csv'),'utf8');const csv=buildTemplate(header,'endpoint-metrics',c);assert.equal(csv.split('\r\n')[0],header.split('\n')[0].trimEnd());assert.match(csv,/"a,""b"/);assert.doesNotMatch(csv,/example-prefill|2026-|180|12.5/);assert.equal(csv.split('\r\n')[2].replace('actual-decode','').replaceAll(',',''),'');
 const hardware=buildTemplate(fs.readFileSync(path.resolve(__dirname,'../../../templates/hardware-metrics.csv'),'utf8'),'hardware-metrics',c);assert.equal(hardware.split('\r\n')[1].replaceAll(',',''),'');assert.doesNotMatch(hardware,/example-gpu|0\.72|2026-/);assert.throws(()=>buildTemplate(header,'endpoint-metrics',{endpoints:[]}),/尚无 Endpoint/);
});
test('fresh INSPECTION/no snapshots explicitly switches source before validate/apply with post-switch version',async()=>{
 const h=harness({items:[cluster('c1','INSPECTION')]});await h.controller.ready;assert.match(h.container.html,/隐藏此集群的巡检读数/);assert.match(h.container.html,/尚无快照或缺少指标/);assert(h.container.html.indexOf('data-manual-action="source"')<h.container.html.indexOf('name="file"'));assert.match(h.container.html,/name="file"[^>]+disabled/);await h.container.upload('my,csv');assert.equal(h.calls.filter(x=>x.url.endsWith('validate')).length,0);await h.container.click('source');assert.deepEqual(h.calls.find(x=>x.url.endsWith('/source')).opts.body,{source:'CSV',expected_version:4});await h.container.upload('my,csv');await h.container.click('apply');const applied=h.calls.find(x=>x.url.endsWith('apply'));assert.deepEqual(applied.opts.body,{kind:'endpoint-metrics',cluster_id:'c1',csv:'my,csv',expected_version:5,normalized_hash:'server-hash'});assert.equal(h.calls.filter(x=>x.url.endsWith('/source')).length,1);assert.match(h.container.html,/导入已保存/);assert.doesNotMatch(h.container.html,/<pre>/);assert.match(h.container.html,/返回大屏/);
});
test('retained historical CSV remains explicit source choice; already CSV validates without redundant PATCH',async()=>{
 const h=harness({items:[{...cluster('c1','INSPECTION'),snapshot:{endpoint_count:12,hardware_count:2}}]});await h.controller.ready;await h.container.upload();assert.equal(h.calls.filter(x=>x.url.endsWith('validate')).length,0);await h.container.click('source');assert.match(h.container.html,/12 个 Endpoint/);await h.container.upload();assert.match(h.container.html,/校验通过/);await h.container.click('source');assert.equal(h.calls.filter(x=>x.url.endsWith('/source')).length,1);
 const active=harness();await active.controller.ready;await active.container.upload();assert.match(active.container.html,/校验通过/);assert.equal(active.calls.filter(x=>x.url.endsWith('/source')).length,0);
});
test('busy locks every target control and suppresses duplicate apply and target changes',async()=>{
 const pending=deferred(),h=harness({request:async url=>url.endsWith('apply')?pending.promise:undefined});await h.controller.ready;await h.container.upload();const operation=h.container.click('apply');assert.equal(h.container['aria-busy'],'true');assert(h.container.controls.every(x=>x.disabled));h.container.change('cluster','c2');await h.container.click('apply');assert.equal(h.calls.filter(x=>x.url.endsWith('apply')).length,1);pending.resolve({data:{changed:true,cluster:cluster()}});await operation;assert.match(h.container.html,/c1集群/);assert.equal(h.calls.filter(x=>x.url.endsWith('apply')).length,1);assert.doesNotMatch(h.container.html,/class="manual-preview"/);
});
test('cluster, kind and file changes invalidate previews before apply',async()=>{
 const h=harness();await h.controller.ready;for(const [name,value] of [['cluster','c2'],['kind','hardware-metrics'],['file','']]){await h.container.upload();h.container.change(name,value);await h.container.click('apply');assert.doesNotMatch(h.container.html,/class="manual-preview"/);}assert.equal(h.calls.filter(x=>x.url.endsWith('apply')).length,0);assert.equal(h.calls.filter(x=>x.url.endsWith('validate')).at(-1).opts.body.kind,'hardware-metrics');
});
test('destroy during file reading, validation, apply, template or initial load never writes detached DOM',async()=>{
 for(const phase of ['load','file','validate','apply','source','template']){const pending=deferred();const h=harness({fetchTemplate:phase==='template'?()=>pending.promise:undefined,request:async url=>((phase==='load'&&url.endsWith('clusters'))||url.endsWith(phase))?pending.promise:undefined});let operation;if(phase==='load')operation=h.controller.ready;else{await h.controller.ready;if(phase==='file')operation=h.container.upload('',{text:()=>pending.promise});if(phase==='validate')operation=h.container.upload();if(phase==='apply'){await h.container.upload();operation=h.container.click('apply');}if(phase==='source'){h.setItems([cluster('c1','INSPECTION')]);await h.controller.refresh();operation=h.container.click('source');}if(phase==='template')operation=h.container.click('template');}h.controller.destroy();const writes=h.container.writes;pending.resolve(phase==='template'?'endpoint_code,sampled_at':phase==='file'?'csv':{data:phase==='load'?{items:[cluster()]}:phase==='apply'?{cluster:cluster(),changed:true}:{row_count:1,summary:{},expected_version:4,normalized_hash:'h'}});await operation;assert.equal(h.container.writes,writes,phase);assert.deepEqual(h.container.handlers,{});assert.equal(h.downloads.length,0);}
});
test('apply saved then refresh failed preserves success, removes repeat apply and blocks source until refresh',async()=>{
 let reads=0;const h=harness({request:async url=>{if(url.endsWith('clusters')&&++reads>1)throw new Error('refresh offline');if(url.endsWith('apply'))return {data:{changed:true,cluster:{...cluster(),version:5,snapshot:{endpoint_count:1}}}};}});await h.controller.ready;await h.container.upload();await h.container.click('apply');assert.match(h.container.html,/导入已保存/);assert.match(h.container.html,/不要重复导入/);assert.doesNotMatch(h.container.html,/class="manual-preview"/);await h.container.click('apply');await h.container.click('source');assert.equal(h.calls.filter(x=>x.url.endsWith('apply')).length,1);assert.equal(h.calls.filter(x=>x.url.endsWith('/source')).length,0);assert.match(h.container.html,/data-permanent-disabled="true"/);
});
test('validation errors include row details without writes; oversized files never validate',async()=>{
 const h=harness({request:async url=>{if(url.endsWith('validate'))throw Object.assign(new Error('CSV error'),{payload:{error:{details:{rows:[{row:2,field:'sampled_at',message:'必须带时区'}]}}}});}});await h.controller.ready;await h.container.upload();assert.match(h.container.html,/第 2 行 · sampled_at：必须带时区/);assert.match(h.container.html,/未保存任何数据/);await h.container.upload('',{size:1048577});assert.equal(h.calls.filter(x=>x.url.endsWith('validate')).length,1);assert.equal(h.calls.filter(x=>x.opts?.method==='PATCH'||x.url.endsWith('apply')).length,0);
});
test('apply/source failures require refresh and new validation; CSV already active needs no PATCH',async()=>{
 const h=harness({request:async url=>{if(url.endsWith('apply')||url.endsWith('/source'))throw new Error('VERSION_CONFLICT');}});await h.controller.ready;await h.container.upload();await h.container.click('apply');assert.match(h.container.html,/先刷新状态，再重新校验/);assert.doesNotMatch(h.container.html,/class="manual-preview"/);await h.container.click('apply');assert.equal(h.calls.filter(x=>x.url.endsWith('apply')).length,1);
 h.setItems([cluster('c1','INSPECTION')]);await h.controller.refresh();await h.container.click('source');assert.match(h.container.html,/来源切换未确认成功/);await h.container.click('source');assert.equal(h.calls.filter(x=>x.url.endsWith('/source')).length,1);
 const active=harness({items:[cluster('c1','CSV')]});await active.controller.ready;await active.container.click('source');assert.doesNotMatch(active.container.html,/data-manual-action="source"/);assert.equal(active.calls.filter(x=>x.url.endsWith('/source')).length,0);
});
test('operator is read only; empty directory routes to existing configuration; template download scope correct',async()=>{
 const h=harness({canWrite:false});await h.controller.ready;await h.container.upload();await h.container.click('apply');await h.container.click('source');assert.equal(h.calls.length,1);assert.match(h.container.html,/当前接口不可写/);assert.doesNotMatch(h.container.html,/name="file"/);await h.container.click('template');assert.match(h.downloads[0].text,/c1-prefill/);assert.doesNotMatch(h.downloads[0].text,/example|123/);assert.equal(h.downloads[0].filename,'c1-code-endpoint-metrics.csv');const empty=harness({items:[]});await empty.controller.ready;assert.match(empty.container.html,/view=monitoring/);assert.match(empty.container.html,/暂无可选集群/);
});
test('integration route, script cache marks and separate TV tab are wired',()=>{
 const gateway=fs.readFileSync(path.resolve(__dirname,'../index.html'),'utf8'),app=fs.readFileSync(path.resolve(__dirname,'../app.js'),'utf8'),portal=fs.readFileSync(path.resolve(__dirname,'../../screen/index.html'),'utf8');assert.match(gateway,/data-route="manual-import"/);assert.match(gateway,/manual-import\.js\?v=direct-access-v1/);assert.match(gateway,/manual-import\.css\?v=direct-access-v1/);assert.match(app,/manualImportController\?\.destroy\(\)/);assert.match(app,/startsWith\('manual-import-'\)/);assert.match(app,/\['catalog','monitoring','manual-import'\]/);assert.match(portal,/<a href="\/gateway\/\?view=manual-import&amp;v=manual-import-2" target="_blank" rel="noopener">/);
});

test('truthful mock and delivered backend share the explicit CSV prerequisite',async()=>{
 const source=fs.readFileSync(path.resolve(__dirname,'../../../backend/control/monitoring.py'),'utf8');assert.match(source,/def metric_plan\(kind,rows,cluster\):\s+if cluster.monitoring_source!='CSV':raise APIError\('SOURCE_CONFLICT'/);const h=harness({items:[cluster('c1','INSPECTION')]});await h.controller.ready;await h.container.upload();await h.container.click('apply');assert.equal(h.calls.length,1);assert.match(h.container.html,/data-manual-action="source" data-permanent-disabled="false"/);
});
test('unknown apply requires successful refresh even after another file, type, target or template',async()=>{
 let lose=true;const h=harness({request:async url=>{if(url.endsWith('apply')&&lose)throw new Error('connection lost');}});await h.controller.ready;await h.container.upload();await h.container.click('apply');const validates=h.calls.filter(x=>x.url.endsWith('validate')).length;await h.container.click('template');assert.match(h.container.html,/先刷新状态/);for(const [name,value] of [['file','other'],['kind','hardware-metrics'],['cluster','c2']]){h.container.change(name,value);await h.container.upload();await h.container.click('apply');await h.container.click('source');assert.match(h.container.html,/先刷新状态/);assert.match(h.container.html,/name="file"[^>]+data-permanent-disabled="true"/);}assert.equal(h.calls.filter(x=>x.url.endsWith('validate')).length,validates);assert.equal(h.calls.filter(x=>x.url.endsWith('apply')).length,1);assert.equal(h.calls.filter(x=>x.url.endsWith('/source')).length,0);lose=false;await h.controller.refresh();await h.container.upload();assert.equal(h.calls.filter(x=>x.url.endsWith('validate')).length,validates+1);await h.container.click('apply');assert.match(h.container.html,/导入已保存/);
});
test('source saved then refresh failed blocks validate until refreshed and keeps the saved outcome',async()=>{
 let reads=0,failRefresh=true;const h=harness({items:[cluster('c1','INSPECTION')],request:async url=>{if(url.endsWith('clusters')&&++reads>1&&failRefresh)throw new Error('offline');}});await h.controller.ready;await h.container.click('source');assert.match(h.container.html,/CSV 来源已启用/);assert.match(h.container.html,/集群状态刷新失败/);for(const name of ['file','kind','cluster']){h.container.change(name,name==='cluster'?'c1':name==='kind'?'endpoint-metrics':'other');await h.container.upload();}assert.equal(h.calls.filter(x=>x.url.endsWith('validate')).length,0);assert.equal(h.calls.filter(x=>x.url.endsWith('/source')).length,1);await h.controller.refresh();assert.match(h.container.html,/CSV 来源已启用/);await h.container.upload();assert.equal(h.calls.filter(x=>x.url.endsWith('validate')).length,0);failRefresh=false;await h.controller.refresh();await h.container.upload();assert.match(h.container.html,/校验通过/);assert.equal(h.calls.filter(x=>x.url.endsWith('validate')).length,1);
});
test('failed refresh with prior visible catalog locks imports and source across target changes',async()=>{
 let fail=false;const h=harness({items:[cluster(),cluster('c2','INSPECTION')],request:async url=>{if(url.endsWith('clusters')&&fail)throw new Error('offline');}});await h.controller.ready;fail=true;await h.controller.refresh();await h.container.upload();h.container.change('cluster','c2');await h.container.click('source');await h.container.upload();assert.equal(h.calls.filter(x=>x.url.endsWith('validate')).length,0);assert.equal(h.calls.filter(x=>x.url.endsWith('/source')).length,0);assert.match(h.container.html,/集群状态未确认/);fail=false;await h.controller.refresh();await h.container.click('source');await h.container.upload();assert.match(h.container.html,/校验通过/);
});
test('directory identities reject formula/control export sinks without modifying or dropping codes',async()=>{
 const unsafe=['=1+1','+1','-1','@SUM(A1)','  =1','\tcode','code\rX','code\nX','foo\u0000bar',' =<img src=x>'];for(const code of unsafe){const c=cluster();c.endpoints=[{code:'safe'},{code}];const h=harness({items:[c]});await h.controller.ready;await h.container.click('template');assert.equal(h.downloads.length,0,code);assert.match(h.container.html,/资源与关系录入中修正目录编码/);assert.doesNotMatch(h.container.html,/<img src=x>/);assert.equal(c.endpoints[1].code,code);}
 const c=cluster();c.endpoints=[{code:'safe,code"quoted'}];const h=harness({items:[c]});await h.controller.ready;await h.container.click('template');assert.equal(h.downloads.length,1);assert.match(h.downloads[0].text,/"safe,code""quoted"/);assert.equal(c.endpoints[0].code,'safe,code"quoted');
});
