const test=require('node:test'),assert=require('node:assert/strict');
global.KeySnapshot={readKeySnapshot:async({id,request})=>request(id)};
const {buildRows,load,MAX_KEYS,MAX_ROWS,CONCURRENCY}=require('../overview-mapping.js');
const catalog={teams:[{id:'t',name:'Team'}],models:[{id:'m',name:'Model',environment_code:'prod',enabled:true}],services:[{id:'s',model_id:'m',environment_code:'prod',enabled:true}],endpoints:[{id:'e1',service_id:'s',cluster_id:'c',environment_code:'prod',address_ref:'svc:8000',enabled:true},{id:'e2',service_id:'s',cluster_id:'c',environment_code:'prod',address_ref:'svc:9000',enabled:true}],clusters:[{id:'c',name:'Cluster',environment_code:'prod'}],'runtime-members':[{id:'r1',endpoint_id:'e1',cluster_id:'c',environment_code:'prod',pod_name:'pod1',node_name:'n1',enabled:true},{id:'r2',endpoint_id:'e1',cluster_id:'c',environment_code:'prod',pod_name:'pod2',node_name:'n2',enabled:true},{id:'wrong',endpoint_id:'e2',cluster_id:'c',environment_code:'dev',pod_name:'wrong',enabled:true}]};
const snap={key:{id:'k',team_id:'t',environment_code:'prod',masked_label:'***K',enabled:true,desired_status:'ACTIVE'},grants:[{model_id:'m',enabled:true}]};
test('one row per exact Key x Model x Endpoint x runtime member, with undeployed endpoint retained',()=>{const {rows}=buildRows(catalog,[snap]);assert.deepEqual(rows.map(x=>[x.endpoint?.id,x.member?.id,x.note]),[['e1','r1',''],['e1','r2',''],['e2',undefined,'未登记运行成员']]);});
test('no grant and no service preserve explicit configuration rows',()=>{const noGrant=buildRows(catalog,[{...snap,grants:[]}]).rows;assert.equal(noGrant[0].note,'未配置模型授权');const noService=buildRows({...catalog,services:[]},[snap]).rows;assert.equal(noService[0].note,'未登记服务');});
test('bounded grant loading reports truncation and never silently treats failures as no grants',async()=>{let active=0,peak=0,calls=0;const keys=Array.from({length:MAX_KEYS+2},(_,i)=>({id:String(i)}));const result=await load({keys,request:async id=>{active++;peak=Math.max(peak,active);calls++;await new Promise(r=>setTimeout(r,1));active--;return {key:{id},grants:[]};}});assert.equal(result.snapshots.length,MAX_KEYS);assert.equal(result.truncated,true);assert.equal(result.totalKeys,MAX_KEYS+2);assert.ok(peak<=CONCURRENCY);assert.equal(calls,MAX_KEYS);await assert.rejects(load({keys:[{id:'bad'}],request:async()=>{throw Error('denied')}}),/denied/);});
test('disabled runtime and cross-environment service never become an active runtime row',()=>{const changed={...catalog,services:[{...catalog.services[0],environment_code:'dev'}],'runtime-members':[{...catalog['runtime-members'][0],enabled:false}]};assert.equal(buildRows(changed,[snap]).rows[0].note,'未登记服务');const inactive={...catalog,'runtime-members':[{...catalog['runtime-members'][0],enabled:false}]};const rows=buildRows(inactive,[snap]).rows;assert.equal(rows.find(x=>x.endpoint.id==='e1').note,'运行成员已登记但停用');});
test('navigation invalidates in-flight grant reads',async()=>{let current=true;const pending=load({keys:[{id:'k'}],request:async()=>{await new Promise(r=>setTimeout(r,5));return snap;},isCurrent:()=>current});current=false;assert.equal(await pending,null);});

test('high-branch mapping stops at explicit row cap',()=>{const expanded={...catalog,'runtime-members':Array.from({length:MAX_ROWS+1},(_,i)=>({...catalog['runtime-members'][0],id:'r'+i}))};const result=buildRows(expanded,[snap]);assert.equal(result.rows.length,MAX_ROWS);assert.equal(result.truncated,true);});

test('registered disabled member is named as disabled, not unregistered or shown as active',()=>{const disabled={...catalog,'runtime-members':[{...catalog['runtime-members'][0],enabled:false}]};const row=buildRows(disabled,[snap]).rows.find(x=>x.endpoint.id==='e1');assert.equal(row.note,'运行成员已登记但停用');assert.equal(row.member,null);});
