const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const live=require('../live-provider.js');
function setup(name){const window={};const nodes={};const root={querySelector(id){return nodes[id]??=( {innerHTML:'',classList:{add(){}}} );}};const document={querySelector:()=>root};vm.runInNewContext(fs.readFileSync(require('node:path').join(__dirname,'../'+name),'utf8'),{window,document});return {renderer:window.ScreenRenderers[name==='restored01.js'?'01':'02'],root,nodes,topology:window.OverviewTopology?.topology};}
const esc=x=>String(x??'').replaceAll('<','&lt;');
function ctx(data){return {data,state:{},now:Date.parse('2026-09-26T01:00:00Z'),e:esc,m:(x,n=0)=>Number(x).toFixed(n),catalog:{},ageState:live.freshness,endpointState:live.endpointState,source:()=>'<div>UNVERIFIED</div>',stateLabel:x=>x,catalogOrigin:()=>'',observationOrigin:()=>''};}
function device(id,type){return {id,name:id,resource_type:type,host_id:'host1',gpu_uuid:type==='GPU_POOL'?'GPU1':'',data_state:'UNVERIFIED',metrics:Object.fromEntries(['cpu_busy_ratio','utilization_ratio','memory_usage_ratio','temperature_celsius'].map(k=>[k,{state:'AVAILABLE',quality:'VALID',value:k==='temperature_celsius'?64:.625,unit:k==='temperature_celsius'?'°C':'ratio',collected_at:'2026-09-26T01:00:00Z'}])),observation:{demo:true,origin:'UNVERIFIED',max_age_seconds:300,source_window:{end:'2026-09-26T01:00:00Z'}}};}
test('01 only five single-device slots, quality/age and pause preserve truthful values',()=>{const {renderer,root,nodes,topology}=setup('restored01.js'),data={summary:{},hardware:[device('GPU A','GPU_POOL'),device('GPU B','GPU_POOL'),device('Host A','HOST')]},c=ctx(data);renderer.bind(root,c);assert.match(nodes['#c-gpu-1'].innerHTML,/62.5%/);assert.match(nodes['#c-compute-mem'].innerHTML,/62.5%/);assert.match(nodes['#c-gpu-3'].innerHTML,/64.0°C/);assert.match(nodes['#c-gpu-1'].innerHTML,/演示 · 未验证/);assert.match(nodes['#c-gpu-1'].innerHTML,/title="[^"]*DEMO \/ UNVERIFIED/);assert.match(nodes['#overview-gpu-device'].innerHTML,/<button data-overview-inspect="GPU A">GPU A<\/button>/);assert.match(nodes['#overview-gpu-device'].innerHTML,/host1 · GPU1/);c.state.overviewInspect='GPU A';const detail=topology(c);assert.match(detail,/完整名称<\/strong><span>GPU A<\/span>/);assert.match(detail,/ID GPU A/);assert.match(nodes['#c-gpu-4'].innerHTML,/未接入/);for(let i=0;i<12;i++)renderer.tick(c);assert.match(nodes['#c-gpu-1'].innerHTML,/GPU B/);c.state.paused=true;for(let i=0;i<24;i++)renderer.tick(c);assert.match(nodes['#c-gpu-1'].innerHTML,/GPU B/);data.hardware[1].metrics.utilization_ratio.quality='RESET';renderer.tick(c);assert.doesNotMatch(nodes['#c-gpu-1'].innerHTML,/62.5%/);c.now+=301000;renderer.tick(c);assert.match(nodes['#c-gpu-2'].innerHTML,/STALE/);assert.doesNotMatch(nodes['#c-gpu-2'].innerHTML,/62.5%/);});
test('02 approved values belong to selected endpoint, ratio converts once and no additive bar',()=>{const {renderer}=setup('restored02.js');const ep=(id,n)=>({id,name:id,role:'PREFILL',service_id:'g',metrics:Object.fromEntries([['e2e_p99_ms',n],['ttft_p95_ms',n+1],['tpot_p95_ms',n+2],['ttft_e2e_ratio',.125]].map(([k,v])=>[k,{state:'AVAILABLE',value:v,unit:k.endsWith('ratio')?'ratio':'ms'}]))});const data={items:[{id:'g',name:'g',endpoints:[ep('A',10),ep('B',20)]}]},c=ctx(data);c.state.endpoint='B';const html=renderer.render(data,c);assert.match(html,/E2E P99 <b>20.0<small>ms/);assert.match(html,/TTFT P95 <b>21.0<small>ms/);assert.match(html,/TPOT P95<\/span><b>22.0<small>ms/);assert.match(html,/TTFT \/ E2E<\/span><b>12.5<small>%/);assert.match(html,/单 Endpoint · 独立分位数/);assert.doesNotMatch(html,/pd-time-track/);assert.doesNotMatch(html,/Queue Time|Prefill Time|Cache Usage|Preemption/);});
test('01 historical CSV hardware retains value with visible sampling label but remains UNKNOWN',()=>{const {renderer,root,nodes}=setup('restored01.js'),row=device('CSV GPU','GPU_POOL'),old='2025-01-01T00:00:00Z';row.data_state='CSV_SNAPSHOT';row.status='OK';row.observation={source_type:'CSV',data_state:'CSV_SNAPSHOT',sampled_at:old,source_window:{end:old}};Object.values(row.metrics).forEach(p=>p.collected_at=old);const c=ctx({summary:{},hardware:[row]});renderer.bind(root,c);assert.match(nodes['#c-gpu-1'].innerHTML,/62.5%/);assert.match(nodes['#c-gpu-1'].innerHTML,/CSV 快照/);assert.match(nodes['#c-gpu-1'].innerHTML,/2025-01-01/);assert.equal(live.endpointState(row,c.now),'UNKNOWN');row.observation.source_type='INSPECTION';renderer.tick(c);assert.doesNotMatch(nodes['#c-gpu-1'].innerHTML,/62.5%/);});
