const {test}=require('node:test');const assert=require('node:assert/strict');const {LiveProvider,revision,freshness,endpointState}=require('../live-provider.js');const {metric,escape}=require('../api.js');
const tick=()=>new Promise(r=>setImmediate(r));
function doc(){return {hidden:false,events:new Map(),addEventListener(n,f){this.events.set(n,f)},removeEventListener(n){this.events.delete(n)}};}
test('null/NaN values never coerce to zero, user values escape',()=>{for(const v of [null,undefined,NaN,Infinity,'0'])assert.equal(metric(v),'—');assert.equal(metric(0),'0');assert.equal(escape('<script>"&'), '&lt;script&gt;&quot;&amp;');});
test('view revisions reject malformed input without lexical comparisons',()=>{assert.ok(revision('11')>revision(9));assert.throws(()=>revision('a'));});
test('older/in-flight response cannot overwrite new view; same revision ages',async()=>{const queue=[];const values=[];let ages=0;const p=new LiveProvider({path:'x',document:doc(),request:()=>new Promise(r=>queue.push(r)),onData:v=>values.push(v.view_revision),onAge:()=>ages++,onError:()=>{},interval:999999});p.start();const old=queue.shift();p.poll();queue.shift()({view_revision:5,data:{name:'new'}});await tick();old({view_revision:2,data:{name:'old'}});await tick();assert.deepEqual(values,[5]);p.poll();queue.shift()({view_revision:4});await tick();assert.deepEqual(values,[5]);p.poll();queue.shift()({view_revision:5});await tick();assert.equal(ages,1);p.stop();});
test('hidden document aborts and suspends network; resumes once and stop removes timers/listener',async()=>{const d=doc();let count=0;const p=new LiveProvider({path:'x',document:d,request:async()=>{count++;return {view_revision:1}},onData:()=>{},onError:()=>{}});p.start();await tick();d.hidden=true;d.events.get('visibilitychange')();await p.poll();assert.equal(count,1);d.hidden=false;d.events.get('visibilitychange')();await tick();assert.equal(count,2);p.stop();assert.equal(d.events.size,0);});
test('repeated server receipts never refresh source age',()=>{const item={data_state:'FRESH',source_window:{end:new Date(0).toISOString()},max_age_seconds:300};assert.equal(freshness(item,299000),'FRESH');assert.equal(freshness({...item,served_at:new Date().toISOString()},301000),'STALE');});
test('invalid renderer contract preserves the last accepted value and revision',async()=>{let incoming={view_revision:1,data:{valid:true}},errors=0;const p=new LiveProvider({path:'x',document:doc(),request:async()=>incoming,onData:v=>{if(!v.data.valid)throw new Error('CONTRACT_INCOMPATIBLE')},onError:()=>errors++});p.start();await tick();incoming={view_revision:2,data:{valid:false}};await p.poll();assert.equal(p.value.view_revision,1);assert.equal(p.lastRevision,1n);assert.equal(errors,1);p.stop();});
test('R7 exact source TTL, local cap and invalid source metadata cannot claim fresh',()=>{const {freshness,endpointState}=require('../live-provider.js'),base={data_state:'FRESH',status:'NORMAL',observation:{max_age_seconds:30,transport_status:'OK',source_window:{end:new Date(0).toISOString()}}};assert.equal(freshness(base,29000),'FRESH');assert.equal(endpointState(base,31000),'UNKNOWN');assert.equal(freshness({...base,observation:{...base.observation,max_age_seconds:1000}},301000),'STALE');for(const ttl of [null,0,-1,NaN,'30',undefined])assert.equal(freshness({...base,observation:{...base.observation,max_age_seconds:ttl}},1000),'UNKNOWN');assert.equal(freshness({...base,observation:{max_age_seconds:30,source_window:{end:'bad'}}},1000),'UNKNOWN');});
test('R7 inspector transport error disqualifies current conclusion but retains last-known numbers',()=>{const {endpointState,sourceTransport}=require('../live-provider.js'),x={data_state:'FRESH',status:'CRITICAL',metrics:{waiting:{value:9}},observation:{max_age_seconds:30,source_window:{end:new Date(0).toISOString()},transport_status:'HTTP_503'}};assert.equal(endpointState(x,1000),'UNKNOWN');assert.equal(sourceTransport(x),'HTTP_503');assert.equal(x.metrics.waiting.value,9);});

test('CSV snapshots retain old values only with both explicit CSV markers, without live health',()=>{
 const old=new Date(Date.now()-86400000).toISOString();
 const row={data_state:'CSV_SNAPSHOT',status:'OK',observation:{source_type:'CSV',data_state:'CSV_SNAPSHOT',sampled_at:old,source_window:{end:old},max_age_seconds:60,transport_status:'OK'}};
 assert.equal(freshness(row),'CSV_SNAPSHOT');assert.equal(endpointState(row),'UNKNOWN');
 assert.equal(freshness({...row,observation:{...row.observation,source_type:'INSPECTION'}}),'STALE');
 assert.equal(freshness({...row,observation:{...row.observation,data_state:'FRESH'}}),'STALE');
 assert.equal(freshness({...row,observation:{...row.observation,sampled_at:'invalid'}}),'INVALID');
 assert.equal(freshness({...row,observation:{...row.observation,sampled_at:new Date(Date.now()+60000).toISOString()}}),'INVALID');
});
