const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const window={};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../restored01.js'),'utf8'),{window,document:{querySelector:()=>null},Date,Map,Number,Math,encodeURIComponent});
const {directory,endpointLink,topology}=window.OverviewTopology;
const escape=s=>String(s).replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
function context(){return {catalog:{clusters:[{id:'east',name:'华东'},{id:'west',name:'西南'}],services:[{id:'service',name:'同一个跨集群服务',model_id:'m'}],models:[{id:'m',name:'模型'}],endpoints:[]},data:{items:[]},state:{},e:escape,catalogOrigin:()=> '目录来源 DEMO'};}
function ep(id,cluster='west',service='service'){return {id,name:'实例 '+id,cluster_id:cluster,service_id:service,role:'DECODE'};}
test('cross-cluster service edges are built from actual Endpoint IDs',()=>{const c=context();c.catalog.endpoints=[ep('a','east'),ep('b')];c.state.overviewCluster='east';let v=directory(c);assert.deepEqual(Array.from(v.visible[0].visible,x=>x.id),['a']);c.state.overviewCluster='west';v=directory(c);assert.deepEqual(Array.from(v.visible[0].visible,x=>x.id),['b']);assert.equal(v.visible[0].id,'service');});
test('all twelve southwest instances are reachable with current/total counters',()=>{const c=context();c.catalog.endpoints=Array.from({length:12},(_,i)=>ep('ep'+i));c.state.overviewCluster='west';const ids=[];for(let i=0;i<3;i++){c.state.overviewBatches={'west|service':i};const v=directory(c);ids.push(...v.visible[0].visible.map(x=>x.id));assert.match(topology(c),new RegExp(`${i*4+1}–${(i+1)*4} / 12`));assert.match(topology(c),/本帧 4 \/ 12/);}assert.equal(new Set(ids).size,12);});
test('all service pages are reachable and deleted selections are clamped',()=>{const c=context();c.catalog.services=Array.from({length:7},(_,i)=>({id:'s'+i,name:'服务 '+i}));c.catalog.endpoints=c.catalog.services.map(s=>ep('e'+s.id,'west',s.id));c.state.overviewCluster='west';const seen=new Set();let count=directory(c).pages;for(let page=0;page<count;page++){c.state.overviewPage=page;directory(c).visible.forEach(x=>seen.add(x.id));}assert.equal(seen.size,7);c.state.overviewCluster='deleted';c.state.overviewPage=99;c.state.overviewInspect='deleted';const v=directory(c);assert.equal(v.chosen.id,'east');assert.equal(c.state.overviewPage,0);assert.equal(c.state.overviewInspect,'');});
test('unresolved instances stay reachable without a fabricated deployment edge',()=>{const c=context();c.catalog.endpoints=[ep('unknown-cluster','gone'),ep('unknown-service','west','gone'),ep('valid')];c.state.overviewCluster='west';assert.equal(directory(c).chosen.endpoints.length,1);c.state.overviewCluster='__unresolved__';const v=directory(c);assert.equal(v.chosen.cluster,null);assert.equal(v.visible[0].service,null);assert.equal(v.visible[0].visible.length,2);const html=topology(c);assert.doesNotMatch(html,/04\.html\?id=gone/);assert.match(html,/缺少可验证的集群或服务/);});
test('04 exact drilldown uses real service and endpoint IDs with URL escaping',()=>{const url=new URL(endpointLink(ep('endpoint &+','west','service /?')),'http://localhost/');assert.equal(url.pathname,'/04.html');assert.equal(url.searchParams.get('id'),'service /?');assert.equal(url.searchParams.get('endpoint'),'endpoint &+');});
test('names are escaped and inspect exposes full text instead of tooltip-only identity',()=>{const c=context();const name='<script>alert(1)</script>'+ '完整名称'.repeat(40);c.catalog.endpoints=[{...ep('long'),name}];c.state.overviewCluster='west';c.state.overviewInspect='long';const html=topology(c);assert.doesNotMatch(html,/<script>/);assert.match(html,/&lt;script&gt;/);assert.ok(html.includes(escape(name)));assert.match(html,/完整名称<\/strong>/);assert.match(html,/ID long/);assert.doesNotMatch(html,/健康率|实时流量 [0-9]/);});
test('empty and disabled directories never create fake deployment nodes',()=>{const c=context();c.catalog.clusters=[];c.catalog.services=[];c.catalog.endpoints=[{...ep('disabled'),enabled:false}];const v=directory(c);assert.equal(v.endpoints.length,0);assert.equal(v.choices.length,0);assert.match(topology(c),/等待目录数据/);});
test('hardware rotation respects pause while refreshes continue',()=>{const renderer=window.ScreenRenderers['01'];const c={state:{paused:true,hardwareElapsed:11},data:{hardware:[]}};renderer.tick(c);assert.equal(c.state.hardwareElapsed,11);c.state.paused=false;renderer.tick(c);assert.equal(c.state.hardwareElapsed,12);});
