(() => {
  'use strict';
  const C=GatewayDirectoryCore,STORE='gateway.entry-flow.prototype.v1',HISTORY='gateway.entry-flow.history.v1';
  const $=selector=>document.querySelector(selector),esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let catalog=GatewayEntryDirectory.catalog(),dirty=false,errors={};
  const runtime=()=>({namespace:'',workload:'',workloadKind:'Deployment',configuredNodes:[]});
  const instance=role=>({code:C.newId(),clusterCode:C.newId(),role,name:'',address:'',cluster:'',clusterName:'',clusterRegion:''});
  function initial(){return {step:0,reached:0,completed:false,savedAt:'',data:{environment:'DEV',serviceMode:'new',serviceId:'',serviceName:'',serviceCode:C.newId(),deployment:'SPLIT_PD',routerEnabled:false,pdCode:C.newId(),pdName:'',teamMode:'existing',teamId:'',teamName:'',teamCode:C.newId(),businessMode:'existing',businessId:'',businessName:'',businessCode:C.newId(),owner:'',modelMode:'existing',modelId:'',modelName:'',modelCode:C.newId(),keyMode:'later',keyId:'',keyName:'',keyCode:C.newId(),externalRef:'',maskedLabel:'',desiredStatus:'ACTIVE',grant:true,endpoints:[instance('PREFILL'),instance('DECODE'),instance('COMBINED'),instance('ROUTER')],runtimes:[runtime(),runtime(),runtime(),runtime()]}};}
  let state=initial();
  try{const saved=JSON.parse(localStorage.getItem(STORE)||'null');if(saved?.schema===1&&Array.isArray(saved.state?.data?.endpoints))state=saved.state;}catch{}
  function ensure(){const d=state.data;d.environment=C.environmentCode(d.environment);for(const key of ['serviceCode','pdCode','teamCode','businessCode','modelCode','keyCode'])if(!d[key])d[key]=C.newId();d.runtimes||=[];if(d.routerEnabled===undefined)d.routerEnabled=d.endpoints.some(row=>row.role==='ROUTER');for(const role of ['PREFILL','DECODE','COMBINED','ROUTER'])if(!d.endpoints.some(row=>row.role===role)){d.endpoints.push(instance(role));d.runtimes.push(runtime());}d.endpoints.forEach((row,i)=>{row.code||=C.newId();row.clusterCode||=C.newId();d.runtimes[i]||=runtime();if(d.runtimes[i].workloadKind===undefined)d.runtimes[i].workloadKind='';d.runtimes[i].configuredNodes=Array.isArray(d.runtimes[i].configuredNodes)?d.runtimes[i].configuredNodes:[];});}
  ensure();
  const get=path=>path.split('.').reduce((obj,key)=>obj?.[key],state.data);
  function set(path,value){const keys=path.split('.');let obj=state.data;for(const key of keys.slice(0,-1))obj=obj[key];obj[keys.at(-1)]=value;dirty=true;}
  const inEnv=type=>catalog[type].filter(row=>row.environment===get('environment'));
  const name=(kind)=>get(kind+'Mode')==='new'?get(kind+'Name'):catalog[kind==='business'?'businesses':kind+'s'].find(row=>row.id===get(kind+'Id'))?.name||'';
  const id=kind=>get(kind+'Mode')==='new'?get(kind+'Code'):get(kind+'Id');
  const roles={PREFILL:'P · 处理输入',DECODE:'D · 生成输出',COMBINED:'合并推理实例',ROUTER:'Router · 请求路由'};
  const active=()=>get('endpoints').map((row,i)=>({row,i})).filter(({row})=>row.role==='ROUTER'?get('routerEnabled'):get('deployment')==='SPLIT_PD'?['PREFILL','DECODE'].includes(row.role):row.role==='COMBINED');
  function notice(text){$('#notice').hidden=!text;$('#notice').textContent=text;}
  const options=(rows)=>[['','请选择'],...rows.map(row=>[row.id,row.name])];
  function field(path,label,{choices,required=false,hint='',placeholder='',wide=false}={}){const value=get(path)??'',inputId='f-'+path.replaceAll('.','-');return `<div class="field ${wide?'wide':''}"><label for="${inputId}">${label}${required?'<span class="required">必填</span>':'<span class="optional">可选</span>'}</label>${choices?`<select id="${inputId}" data-field="${path}">${choices.map(([key,text])=>`<option value="${esc(key)}" ${value===key?'selected':''}>${esc(text)}</option>`).join('')}</select>`:`<input id="${inputId}" data-field="${path}" value="${esc(value)}" placeholder="${esc(placeholder)}">`}${hint?`<small class="hint">${hint}</small>`:''}<div id="${inputId}-error" class="error" ${errors[path]?'':'hidden'}>${esc(errors[path]||'')}</div></div>`;}
  function entity(kind,label,type,items){const existing=get(kind+'Mode')==='existing';return `<div class="entity-entry"><div class="section-heading"><h3>${label}</h3><div class="choice-group"><button type="button" data-entity="${kind}" data-value="existing" class="choice ${existing?'selected':''}">选择已有${label}</button><button type="button" data-entity="${kind}" data-value="new" class="choice ${!existing?'selected':''}">新增${label}</button></div></div><div class="fields">${existing?field(kind+'Id',label,{choices:options(items||inEnv(type)),required:true,wide:true,hint:!(items||inEnv(type)).length?'此环境尚无记录，可点击新增。':''}):field(kind+'Name',label+'名称',{required:true,wide:true})}${kind==='business'&&!existing?field('owner','负责人',{required:true,wide:true}):''}</div></div>`;}
  function instanceView(row,i){const r=get('runtimes')[i];return `<div class="endpoint"><div class="endpoint-heading"><strong>实例 ${active().filter(item=>item.row.role===row.role).findIndex(item=>item.i===i)+1}</strong><div class="endpoint-actions"><button type="button" data-copy="${i}">复制共同配置</button>${active().filter(item=>item.row.role===row.role).length>1?`<button type="button" data-remove="${i}">移除</button>`:''}</div></div><div class="fields">${field(`endpoints.${i}.name`,row.role==='COMBINED'?'实例名称':row.role==='ROUTER'?'Router 实例名':row.role==='PREFILL'?'P 实例名':'D 实例名',{required:true,placeholder:row.role==='PREFILL'?'prefill-0':row.role==='DECODE'?'decode-0':row.role==='ROUTER'?'router-0':'inference-0'})}${field(`endpoints.${i}.cluster`,'所在 K8s 集群',{required:true,choices:[...options(inEnv('clusters')),['__new__','＋ 登记新集群']]})}${row.cluster==='__new__'?field(`endpoints.${i}.clusterName`,'新集群名称',{required:true})+field(`endpoints.${i}.clusterRegion`,'集群区域'):''}${field(`runtimes.${i}.namespace`,'Namespace（命名空间）',{required:true,placeholder:'inference',hint:'填写该实例实际部署的 Kubernetes 命名空间。'})}${field(`runtimes.${i}.workloadKind`,'部署方式',{required:true,choices:[['','请选择'],['LWS','LWS'],['Deployment','Deployment']]})}${field(`runtimes.${i}.workload`,'工作负载名称',{required:true,placeholder:row.role==='ROUTER'?'router':'inference',hint:'填写 K8s 中对应 LWS 或 Deployment 资源的名称。'})}${field(`endpoints.${i}.address`,'实例访问地址',{required:true,placeholder:'http://10.0.1.20:8000',hint:row.role==='ROUTER'?'填写 Router 接收请求的地址，例如 http://router.inference.svc:8000。':'填写此 P / D 或合并实例监听的地址，例如 http://prefill.inference.svc:8000。'})}</div><div class="configured-nodes"><div class="section-heading"><h3>配置 Node / 部署范围</h3><button type="button" class="button small" data-add-node="${i}">＋ 添加 Node</button></div><p class="hint">登记预期部署节点，可填写多个。实际 Pod、Node UID 和调度结果由采集端提供；当前 Demo 未连接。</p>${r.configuredNodes.map((node,n)=>`<div class="configured-node-row">${field(`runtimes.${i}.configuredNodes.${n}`,'Node 名称',{required:true,placeholder:'worker-node-01'})}<button type="button" data-remove-node="${i}" data-node-index="${n}" aria-label="移除 Node ${n+1}">移除</button></div>`).join('')||'<p class="hint">尚未登记配置节点。</p>'}</div></div>`;}
  function form(){const d=state.data;return `<section class="section"><div class="section-heading"><h2>1. 推理服务</h2><span class="pill neutral">${state.edit?'记录 ID 只读':'UUID 自动生成'}</span></div><div class="fields">${d.serviceMode==='existing'?field('serviceId','为已有推理服务添加实例',{choices:options(inEnv('services').filter(row=>row.model===d.modelId)),required:true,wide:true}):field('serviceName','推理服务名',{required:true,placeholder:'例如：代码辅助推理'})}${field('environment','环境',{required:true,choices:[['PRD','PRD · 生产'],['DR','DR · 灾备'],['STG','STG · 预发布'],['DEV','DEV · 开发']]})}</div>${entity('model','模型','models')}<details class="record-identity"><summary>记录身份（系统维护）</summary><code>${esc(id('service'))}</code></details></section><section class="section"><h2>2. 团队与业务归属</h2>${entity('team','团队','teams')}${entity('business','业务','businesses',d.teamMode==='existing'?inEnv('businesses').filter(row=>row.team===d.teamId):[])}</section><section class="section"><div class="section-heading"><h2>3. 部署信息</h2><small>同一服务 · ${esc(d.environment)}</small></div><div class="fields">${field('deployment','是否 P/D 分离',{required:true,choices:[['SPLIT_PD','是 · 分别登记 P 和 D 实例'],['COMBINED','否 · 登记合并实例']]})}${field('routerEnabled','是否部署 Router',{required:true,choices:[[false,'否'],[true,'是 · 登记 Router 实例']]})}</div><p class="hint deployment-help">${d.deployment==='SPLIT_PD'?'新服务的 P、D 和 Router 自动归入同一部署组；编辑时保留原有分组关系。':'合并实例同时处理输入与输出，无需 P/D 分组。'}实例地址只登记，不会连接或探测。</p>${(d.deployment==='SPLIT_PD'?['PREFILL','DECODE']:['COMBINED']).concat(d.routerEnabled?['ROUTER']:[]).map(role=>`<div class="instance-role-group"><h3>${esc(roles[role])}</h3>${active().filter(item=>item.row.role===role).map(({row,i})=>instanceView(row,i)).join('')}<button type="button" class="add-row" data-add-role="${role}">＋ 添加${role==='PREFILL'?' P':role==='DECODE'?' D':role==='ROUTER'?' Router':'合并'}实例</button></div>`).join('')}</section><section class="section"><h2>4. 调用授权</h2><div class="fields">${field('keyMode','是否登记 Key 引用',{choices:[['later','暂不登记，稍后补充'],['new','登记新的 Key 引用'],['existing','复用已有 Key 引用']],required:true,wide:true})}${d.keyMode==='new'?field('keyName','Key 引用名称',{required:true})+field('externalRef','外部 Key 引用 ID',{required:true,hint:'填写外部系统已有的字符串引用；这不是本目录 UUID，不会自动创建凭据。'})+field('maskedLabel','脱敏标签',{required:true,placeholder:'demo-••••-0003'})+field('desiredStatus','配置意图',{choices:[['ACTIVE','启用'],['SUSPENDED','暂停']],required:true}):d.keyMode==='existing'?field('keyId','已有 Key 引用',{required:true,wide:true,choices:options(inEnv('keys').filter(row=>row.team===d.teamId&&row.business===d.businessId))}):''}</div>${d.keyMode!=='later'?`<label class="check"><input type="checkbox" data-field="grant" ${d.grant?'checked':''}>授权访问本服务使用的模型</label>`:''}<p class="hint">执行端未连接；保存配置不会签发密钥或部署服务。</p></section>`;}
  function output(){const d=state.data;return {kind:'synthetic-entry-flow-demo',environment:d.environment,saved_to:'browser-only',effective_status:'NOT_CONNECTED',team:{name:name('team'),mode:d.teamMode,reference:id('team')},business:{name:name('business'),mode:d.businessMode,reference:id('business'),owner:d.owner},model:{name:name('model'),mode:d.modelMode,reference:id('model')},service:{name:name('service'),mode:d.serviceMode,reference:id('service'),deployment:d.deployment},pd_group:d.deployment==='SPLIT_PD'?{code:d.pdCode,name:d.pdName||name('service')+' · 默认部署组'}:null,pd_groups:d.deployment==='SPLIT_PD'?(d.savedPdGroups?.length?d.savedPdGroups:[{code:d.pdCode,name:d.pdName||name('service')+' · 默认部署组'}]):[],new_clusters:[...new Map(active().filter(({row})=>row.cluster==='__new__').map(({row})=>[row.clusterCode,{code:row.clusterCode,name:row.clusterName,region:row.clusterRegion||''}])).values()],endpoints:active().map(({row,i})=>({code:row.code,name:row.name,role:row.role,pd_group_code:row.pdGroupCode||d.pdCode,address_ref:row.address,cluster:{id:row.cluster==='__new__'?row.clusterCode:row.cluster,name:row.cluster==='__new__'?row.clusterName:catalog.clusters.find(c=>c.id===row.cluster)?.name},namespace:d.runtimes[i].namespace,workload_ref:d.runtimes[i].workload,workload_kind:d.runtimes[i].workloadKind,configured_nodes:[...d.runtimes[i].configuredNodes]})),key:d.keyMode==='later'?null:{name:d.keyName,code:d.keyMode==='new'?d.keyCode:null,reference:d.keyMode==='new'?d.externalRef:d.keyId,masked_label:d.maskedLabel,desired_status:d.desiredStatus},configured_relationships:{business_service_dependency:true,key_model_authorization:d.keyMode!=='later'&&d.grant}};}
  function validate(){const err={},d=state.data,required=path=>{if(!String(get(path)??'').trim())err[path]='请填写此项。';};for(const kind of ['team','business','model','service'])required(kind+(d[kind+'Mode']==='new'?'Name':'Id'));if(d.businessMode==='new')required('owner');active().forEach(({row,i})=>{for(const key of ['name','cluster','address'])required(`endpoints.${i}.${key}`);required(`runtimes.${i}.namespace`);required(`runtimes.${i}.workload`);required(`runtimes.${i}.workloadKind`);if(row.cluster==='__new__')required(`endpoints.${i}.clusterName`);if(row.address&&!row.address.startsWith('demo-only:')&&!C.isAddress(row.address))err[`endpoints.${i}.address`]='请填写 http:// 或 https:// 开头的地址（不含账号密码）。';const r=d.runtimes[i];r.configuredNodes.forEach((node,n)=>{if(!String(node).trim())err[`runtimes.${i}.configuredNodes.${n}`]='请填写 Node 名称或移除此行。';else if(r.configuredNodes.filter(item=>String(item).trim()===String(node).trim()).length>1)err[`runtimes.${i}.configuredNodes.${n}`]='同一实例的 Node 名称不能重复。';});});if(d.keyMode==='new'){for(const path of ['keyName','externalRef','maskedLabel'])required(path);if(d.maskedLabel&&!/[•*]/.test(d.maskedLabel))err.maskedLabel='请填写包含 • 或 * 的脱敏标签。';}if(d.keyMode==='existing')required('keyId');return err;}
  function status(){$('#draft-state').textContent=state.completed?'本次服务已保存':dirty?'有未保存的输入':state.savedAt?'草稿已保存 · '+state.savedAt:'尚未保存草稿';$('#entry-session-label').textContent=(state.completed?'上次保存结果':'当前服务')+(name('service')?' · '+name('service'):' · 新建');}
  function historyRows(){const rows=JSON.parse(localStorage.getItem(HISTORY)||'[]');if(!Array.isArray(rows))throw Error();return rows;}
  function renderHistory(){try{const rows=historyRows();$('#entry-history').innerHTML='<option value="">历史草稿与记录'+(rows.length?' · '+rows.length:'')+'</option>'+rows.map(row=>`<option value="${esc(row.id)}">${esc(row.name)} · ${row.state.completed?'已保存':'草稿'} · ${esc(row.time)}</option>`).join('');$('#entry-history').disabled=!rows.length;}catch{$('#entry-history').disabled=true;}}
  function render(){ensure();$('#title').textContent=state.completed?'推理服务已保存':state.edit?'编辑推理服务':'新建推理服务';$('#subtitle').textContent=state.completed?'在资源目录中查看或修改；新服务请点击“新建录入”。':'在本页填写服务、部署实例与调用授权，一次保存。';$('#position').textContent='';$('#steps').innerHTML='';$('#form-content').innerHTML=state.completed?`<section class="section result"><h2>${esc(name('service'))}</h2><p>本服务与关联资源已保存到浏览器演示目录。</p><button type="button" class="button primary" data-entry-records>查看已录入记录</button><button type="button" class="button" id="edit-result">编辑本次服务</button></section>`:form();$('#prev').hidden=true;$('#next').hidden=state.completed;$('#next').textContent=state.edit?'保存整项服务修改':'保存整项推理服务';$('#save-draft').hidden=state.completed;$('#example').hidden=state.completed;$('#summary').innerHTML=`<div class="summary-item"><small>推理服务</small><strong>${esc(name('service')||'待填写')}</strong></div><div class="summary-item"><small>环境</small><strong>${esc(get('environment'))}</strong></div><div class="summary-item"><small>部署实例</small><strong>${active().length} 个</strong></div>`;status();renderHistory();for(const path of Object.keys(errors)){const el=$('[data-field="'+path+'"]');if(el){el.setAttribute('aria-invalid','true');el.closest('details')?.setAttribute('open','');}}}
  function save(){state.data.runtimes=state.data.runtimes.map(row=>({namespace:row.namespace||'',workload:row.workload||'',workloadKind:row.workloadKind||'',configuredNodes:[...(row.configuredNodes||[])]}));state.savedAt=new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'});try{localStorage.setItem(STORE,JSON.stringify({schema:1,state}));dirty=false;status();return true;}catch{notice('草稿保存失败，当前输入仍保留，请保留此页。');return false;}}
  function replaceSession(next){try{if(dirty||state.savedAt||state.completed){const rows=historyRows(),snapshot=JSON.stringify(state);if(!rows.some(row=>JSON.stringify(row.state)===snapshot))rows.unshift({id:C.newId(),name:name('service')||'未命名服务',time:new Date().toLocaleString('zh-CN'),state:JSON.parse(snapshot)});localStorage.setItem(HISTORY,JSON.stringify(rows));}localStorage.setItem(STORE,JSON.stringify({schema:1,state:next}));}catch{notice('无法保存历史草稿，当前输入已保留。');return false;}state=next;dirty=false;errors={};const url=new URL(location.href);url.searchParams.delete('service');history.replaceState(null,'',url);render();notice('');return true;}
  function startNew(){if(replaceSession(initial()))notice('已开始新服务录入，之前内容保留在历史记录中。');}
  GatewayEntryDirectory.editService=context=>{
    const db=context.expected,service=db.services.find(row=>row.code===context.serviceId);if(!service)return;
    const next=initial(),d=next.data,business=db.businesses.find(row=>row.code===context.previousBusiness);
    Object.assign(d,{environment:C.environmentCode(service.environment),serviceName:service.name,serviceCode:service.code,serviceMode:'new',deployment:service.deployment_mode,modelMode:'existing',modelId:service.model_code,teamMode:business?'existing':'new',teamId:business?.team_code||'',businessMode:business?'existing':'new',businessId:business?.code||'',owner:business?.owner||'',keyMode:'later'});
    d.savedPdGroups=db.pdgroups.filter(row=>row.service_code===service.code);d.pdCode=d.savedPdGroups[0]?.code||C.newId();
    d.endpoints=db.endpoints.filter(row=>row.service_code===service.code).map(row=>({...instance(row.role),code:row.code,name:row.name,address:row.address_ref,cluster:row.cluster_code,pdGroupCode:row.pd_group_code}));
    d.runtimes=d.endpoints.map(row=>{const endpoint=db.endpoints.find(ep=>ep.code===row.code),member=db.runtimes.find(r=>r.endpoint_code===row.code);return {namespace:endpoint.namespace||member?.namespace||'',workload:endpoint.workload_ref||member?.workload_ref||'',workloadKind:endpoint.workload_kind||member?.workload_kind||'',configuredNodes:[...(endpoint.configured_nodes||[])]};});
    d.routerEnabled=d.endpoints.some(row=>row.role==='ROUTER');next.edit=context;
    if(replaceSession(next)){const url=new URL(location.href);url.searchParams.set('service',service.code);history.replaceState(null,'',url);notice('正在编辑整项服务。原有 Key 授权及其他业务关联保留；本页可补充授权。');}
  };
  GatewayEntryDirectory.startNew=startNew;GatewayEntryDirectory.prepareLeave=()=>{if(dirty)save();};
  function demo(){const next=initial(),d=next.data;Object.assign(d,{teamId:'dev',businessId:'coding',modelId:'coder',serviceName:'代码辅助推理',routerEnabled:true,keyMode:'later'});d.endpoints.forEach((row,i)=>{row.name={PREFILL:'prefill-0',DECODE:'decode-0',COMBINED:'inference-0',ROUTER:'router-0'}[row.role];row.cluster='southwest';row.address='http://'+row.name+'.example.invalid:8000';d.runtimes[i]={...runtime(),namespace:'inference',workload:row.name,workloadKind:row.role==='ROUTER'?'Deployment':'LWS',configuredNodes:['demo-worker-01','demo-worker-02']};});if(replaceSession(next)){dirty=true;render();notice('已填入 P、D、Router 合成示例。example.invalid 为演示地址，不连接真实系统。');}}
  document.addEventListener('click',event=>{const b=event.target.closest('button');if(!b)return;if(b.dataset.entity){set(b.dataset.entity+'Mode',b.dataset.value);if(b.dataset.entity==='team'){state.data.businessId='';state.data.keyId='';if(b.dataset.value==='new')state.data.businessMode='new';}render();}if(b.dataset.addRole){state.data.endpoints.push(instance(b.dataset.addRole));state.data.runtimes.push(runtime());dirty=true;render();}if(b.dataset.copy!==undefined){const i=Number(b.dataset.copy),row=state.data.endpoints[i];state.data.endpoints.push({...row,code:C.newId(),clusterCode:C.newId(),name:'',address:''});state.data.runtimes.push({...state.data.runtimes[i],configuredNodes:[...state.data.runtimes[i].configuredNodes]});dirty=true;render();}if(b.dataset.addNode!==undefined){state.data.runtimes[Number(b.dataset.addNode)].configuredNodes.push('');dirty=true;render();}if(b.dataset.removeNode!==undefined){state.data.runtimes[Number(b.dataset.removeNode)].configuredNodes.splice(Number(b.dataset.nodeIndex),1);dirty=true;render();}if(b.dataset.remove!==undefined){const i=Number(b.dataset.remove);state.data.endpoints.splice(i,1);state.data.runtimes.splice(i,1);dirty=true;render();}if(b.id==='reset')startNew();if(b.id==='example')demo();if(b.id==='save-draft'&&save())notice('整页草稿已保存。');if(b.id==='edit-result')GatewayEntryDirectory.edit('services',id('service'));});
  function input(event){const el=event.target,path=el.dataset.field;if(!path)return;set(path,el.type==='checkbox'?el.checked:path==='routerEnabled'?el.value==='true':el.value);delete errors[path];el.removeAttribute('aria-invalid');const error=$('#'+el.id+'-error');if(error)error.hidden=true;status();if(event.type!=='change')return;if(path==='environment'){for(const kind of ['team','business','model','service']){state.data[kind+'Id']='';state.data[kind+'Mode']=kind==='service'?'new':inEnv(kind==='business'?'businesses':kind+'s').length?'existing':'new';}state.data.keyId='';state.data.keyMode='later';state.data.endpoints.forEach(row=>{row.cluster='';});}if(path==='teamId'){state.data.businessId='';state.data.keyId='';}if(path==='businessId')state.data.keyId='';if(path==='serviceId'){const service=catalog.services.find(row=>row.id===el.value);if(service)state.data.deployment=service.deployment;}if(['environment','teamId','businessId','serviceId','deployment','routerEnabled','keyMode'].includes(path)||/^endpoints\.\d+\.cluster$/.test(path))render();}
  document.addEventListener('input',input);document.addEventListener('change',input);
  $('#entry-history').onchange=event=>{try{const row=historyRows().find(item=>item.id===event.target.value);if(row)replaceSession(row.state);}catch{notice('历史记录无法读取。');}};
  $('#flow-form').onsubmit=event=>{event.preventDefault();if(state.completed)return;errors=validate();if(Object.keys(errors).length){render();const first=$('[aria-invalid="true"]');first?.focus();first?.scrollIntoView({block:'center'});notice('请补齐标出的信息；其他输入已保留。');return;}const result=state.edit?GatewayEntryDirectory.commitService(output(),state.edit):GatewayEntryDirectory.commitWizard(output());if(!result.ok){notice('尚未保存：'+result.message);$('#notice').scrollIntoView({block:'center'});return;}state.completed=true;state.directorySaved=true;delete state.edit;save();render();notice('整项推理服务及实例、部署位置和配置关系已保存。');window.scrollTo({top:0,behavior:'instant'});};
  window.addEventListener('demo-directory-change',()=>{catalog=GatewayEntryDirectory.catalog();render();});window.addEventListener('beforeunload',event=>{if(dirty){event.preventDefault();event.returnValue='';}});render();
  const requestedService=GatewayEntryDirectory.pendingServiceId||(new URLSearchParams(location.search).get('mode')==='wizard'?new URLSearchParams(location.search).get('service'):null);if(requestedService){if(state.edit?.serviceId===requestedService&&!state.completed){const url=new URL(location.href);url.searchParams.set('service',requestedService);history.replaceState(null,'',url);}else GatewayEntryDirectory.editService(GatewayEntryDirectory.serviceContext(requestedService));delete GatewayEntryDirectory.pendingServiceId;}
})();
