(()=>{'use strict';const pages={'01':'01.html','02':'02.html','03':'03.html','04':'04.html','05':'05.html'},aliases={'智算.html':'01','02-PD运行诊断.html':'02','02-GPU资源池运行安全.html':'02','03-基础设施异常资源定位.html':'03','03-Kubernetes运行安全.html':'03','04-推理服务异常对象定位.html':'04','04-LLM推理集群运行安全.html':'04','05-关键应用守望.html':'05'};const frame=document.querySelector('#dashboard-frame'),stage=document.querySelector('#stage'),status=document.querySelector('#load-status');const isDemo=new URLSearchParams(location.search).get('demo')==='1';let current='01',currentURL,playing=false,remaining=90000,last=performance.now(),provider,ready=false,loadTimer;
const identify=url=>{const name=decodeURIComponent(url.pathname.split('/').pop());return Object.keys(pages).find(k=>pages[k]===name)||aliases[name];};
function sync(){document.querySelectorAll('[data-screen]').forEach(b=>{b.setAttribute('aria-pressed',String(b.dataset.screen===current));b.classList.toggle('active',b.dataset.screen===current);});const standaloneURL=new URL(currentURL);standaloneURL.searchParams.delete('embedded');document.querySelector('#standalone').href=standaloneURL.href;const url=new URL(location.href);url.search=currentURL.search;url.searchParams.delete('embedded');url.searchParams.set('screen',current);history.replaceState(null,'',url);}
function fail(message){clearTimeout(loadTimer);status.hidden=false;document.querySelector('#load-message').textContent=message;document.querySelector('#retry').hidden=false;}
function show(id,params=new URLSearchParams()){if(!ready)return;current=pages[id]?id:'01';currentURL=new URL(pages[current],location.href);currentURL.search=params.toString();currentURL.searchParams.delete('screen');currentURL.searchParams.delete('scene');currentURL.searchParams.delete('embedded');if(isDemo)currentURL.searchParams.set('demo','1');remaining=90000;last=performance.now();sync();status.hidden=false;document.querySelector('#retry').hidden=true;document.querySelector('#load-message').textContent='正在加载 '+current+' 观测屏幕…';clearTimeout(loadTimer);loadTimer=setTimeout(()=>fail('加载时间较长，可重试或独立打开'),20000);const embeddedURL=new URL(currentURL);embeddedURL.searchParams.set('embedded','1');frame.src=embeddedURL.href;}
frame.addEventListener('load',()=>{try{const url=new URL(frame.contentWindow.location.href),key=identify(url),doc=frame.contentDocument;if(!key||!doc?.querySelector('.screen'))return;clearTimeout(loadTimer);current=key;currentURL=url;sync();status.hidden=true;syncFrameVisibility();doc.addEventListener('click',ev=>{const a=ev.target.closest('a[href]');if(!a||ev.button!==0||ev.ctrlKey||ev.metaKey||ev.shiftKey||ev.altKey)return;const target=new URL(a.href,url);if(target.origin!==location.origin)return;const next=identify(target);if(next){ev.preventDefault();ev.stopImmediatePropagation();show(next,target.searchParams);}},true);}catch{fail('无法读取观测屏幕，请重试');}});
function syncFrameVisibility(){try{frame.contentDocument?.body?.classList.toggle('portal-hidden',document.hidden);}catch{}}
function fit(){const scale=Math.min(stage.clientWidth/1920,stage.clientHeight/1080);frame.style.transform=`scale(${scale})`;frame.style.left=(stage.clientWidth-1920*scale)/2+'px';frame.style.top=(stage.clientHeight-1080*scale)/2+'px';}new ResizeObserver(fit).observe(stage);fit();
document.addEventListener('click',ev=>{const b=ev.target.closest('[data-screen]');if(b)show(b.dataset.screen);if(ev.target.closest('#critical-watch'))show('05');if(ev.target.closest('#retry'))show(current,currentURL?.searchParams);if(ev.target.closest('#rotation')){playing=!playing;remaining=90000;last=performance.now();document.querySelector('#rotation').textContent=playing?'暂停轮播':'开启轮播';document.querySelector('#rotation').setAttribute('aria-pressed',String(playing));}if(ev.target.closest('#fullscreen')){if(document.fullscreenElement)document.exitFullscreen?.();else document.documentElement.requestFullscreen?.();}});
const timer=setInterval(()=>{const now=performance.now();if(playing&&!document.hidden){remaining-=now-last;if(remaining<=0)show('0'+(Number(current)%5+1));}last=now;document.querySelector('#countdown').textContent=playing?Math.ceil(remaining/1000)+' 秒后切屏':'手动展示';if(status.hidden){try{const url=new URL(frame.contentWindow.location.href);if(url.href!==currentURL.href&&identify(url)){current=identify(url);currentURL=url;sync();}}catch{}}},250);document.addEventListener('visibilitychange',()=>{last=performance.now();syncFrameVisibility();});
(async()=>{try{if(isDemo){ready=true;const q=new URLSearchParams(location.search);document.body.classList.add('demo-mode');document.querySelector('.demo-label').textContent='数据源 SZF机房 · PRD';const apps=DemoData.apps;document.querySelector('#critical-watch-count').textContent=apps.length+' 项 · '+apps.filter(a=>a.business_observed_status==='NORMAL').length+' 正常 / '+apps.filter(a=>a.business_observed_status==='WARNING').length+' 关注';show(q.get('screen')||'01',q);return;}await ControlAPI.ensureAccess();ready=true;const q=new URLSearchParams(location.search);show(q.get('screen')||'01',q);provider=new LiveData.LiveProvider({path:'/api/v1/screens/critical-apps',interval:10000,onData:v=>{document.querySelector('#critical-watch-count').textContent=v.data.items.length+' 项 · 状态未知';document.querySelector('.demo-label').textContent='来源 '+(v.data.data_state||'UNKNOWN');},onError:()=>{document.querySelector('#critical-watch-count').textContent='通信中断 · 状态未知';}});provider.start();}catch(err){fail(err.message);document.querySelector('#critical-watch-count').textContent='接口加载失败';}})();addEventListener('popstate',()=>{const q=new URLSearchParams(location.search);show(q.get('screen'),q);});addEventListener('pagehide',()=>{clearInterval(timer);clearTimeout(loadTimer);provider?.stop();});window.PortalLive={show,get playing(){return playing;}};})();
