(()=>{'use strict';
const A=ControlAPI,e=A.escape,m=A.metric,n=document.body.dataset.screen,app=document.querySelector('#app');
const titles={'01':'全局总览','02':'PD 集群全景','03':'基础设施故障','04':'推理服务故障','05':'关键应用守望'},paths={'01':'overview','02':'pd-groups','03':'infrastructure','04':'services','05':'critical-apps'};
const q=new URLSearchParams(location.search);
// Only the same-origin portal iframe may request compact embedded chrome.
let embedded=false;try{embedded=q.get('embedded')==='1'&&parent!==window&&parent.document.querySelector('#dashboard-frame')?.contentWindow===window;}catch{}
document.body.classList.toggle('screen-embedded',embedded);
const motionPreference=matchMedia('(prefers-reduced-motion: reduce)');let payload=null,provider,transportError='',catalogError='',lastAgeSignature='',hiddenAt=null,catalogLoading=false,motion=!matchMedia('(prefers-reduced-motion: reduce)').matches;
const state={selected:q.get('id')||q.get('cluster')||q.get('service')||'',endpoint:q.get('endpoint')||'',paused:false,cycle:0,manualUntil:0};
const stateLabel=s=>({CSV_SNAPSHOT:'CSV 快照',MISSING:'等待监控数据',UNMAPPED:'尚未绑定数据源',UNVERIFIED:'UNVERIFIED 来源待验证',FRESH:'有效来源窗口',STALE:'来源已过期',UNSUPPORTED:'未接入',UNKNOWN:'状态未知',LOADING:'正在加载',INVALID:'来源无效',SOURCE_ERROR:'巡检通信异常'})[s]||s;
const tag=s=>`<span class="state ${e(s)}">${e(stateLabel(s))}</span>`;
const source=x=>{const o=x?.observation,w=o?.source_window||x?.source_window;if(o?.source_type==='CSV'&&o?.data_state==='CSV_SNAPSHOT')return `<div class="live-source">CSV 快照 · 状态未知 · 保留至下次导入<br>采样时间 ${e(o.sampled_at||w?.end||'—')} · 原始对象口径</div>`;return `<div class="live-source">来源 ${e(o?.origin||'UNVERIFIED')} · ${e(stateLabel(LiveData.freshness(x)))} · 巡检链路 ${e(LiveData.sourceTransport(x))}<br>来源窗口 ${e(w?.start||'—')} ～ ${e(w?.end||'—')} · 原始 Endpoint 口径</div>`;};
const catalogOrigin=()=>{const rows=Object.values(ctx.catalog).flat(),origins=[...new Set(rows.map(x=>x.origin||'UNKNOWN'))];return !origins.length?'目录来源未知':origins.length===1?'目录来源 '+origins[0]:'目录来源混合 · '+origins.join(' / ');};
const observationOrigin=()=>{const origins=[...new Set((payload?.data.items||[]).flatMap(x=>x.endpoints||x.dependency_services?.flatMap(s=>s.endpoints)||[x]).map(x=>x.observation?.origin).filter(Boolean))];return origins.length?origins.join(' / '):'来源未知';};
const ctx={e,m,catalogOrigin,observationOrigin,state,stateLabel,tag,source,ageState:LiveData.freshness,endpointState:LiveData.endpointState,catalog:{},data:null,now:Date.now(),refresh:render,pause,navigate,link:(screen,id,label)=>`<a href="${e(screen)}.html?id=${encodeURIComponent(id)}">${e(label)} ↗</a>`};
function navigate(screen,id,extra={}){const url=new URL(screen+'.html',location.href);if(embedded)url.searchParams.set('embedded','1');if(id)url.searchParams.set('id',id);Object.entries(extra).forEach(([k,v])=>url.searchParams.set(k,v));location.href=url.href;}
function pause(value){state.paused=value;state.cycle=0;state.manualUntil=value?Date.now()+60000:0;syncPause();render();}
function syncPause(){document.body.classList.toggle('screen-paused',state.paused);const b=document.querySelector('#pause');if(b){b.textContent=state.paused?'恢复巡播':'暂停 60s';b.setAttribute('aria-pressed',String(state.paused));}}
function validate(v){const d=v?.data;if(!d||!Array.isArray(d.items)||!d.coverage||!d.summary||!d.source_window)throw new Error('屏幕响应不符合契约');for(const x of d.items){if(typeof x.id!=='string'||typeof x.name!=='string')throw new Error('对象身份不符合契约');if(['02','04'].includes(n)&&!Array.isArray(x.endpoints))throw new Error('Endpoint 集合不符合契约');if(n==='04'&&!Array.isArray(x.configured_businesses))throw new Error('业务依赖集合不符合契约');if(n==='05'&&!Array.isArray(x.service_ids))throw new Error('服务关系集合不符合契约');}return v;}
function render(){if(!payload)return;ctx.data=payload.data;ctx.now=Date.now();const renderer=window.ScreenRenderers?.[n];if(!renderer)throw new Error('屏幕渲染器未加载');app.innerHTML=renderer.render(payload.data,ctx);renderer.bind?.(app,ctx);const origin=document.querySelector('#catalog-origin');if(origin)origin.textContent=catalogOrigin();const snapshot=document.querySelector('.snapshot');if(snapshot)snapshot.textContent=transportError?'通信中断 · 保留旧帧':stateLabel(LiveData.freshness(payload.data));document.querySelector('#app-footer').innerHTML=`<span>${e(catalogOrigin())} / 观测 ${e(observationOrigin())} / ${e(stateLabel(LiveData.freshness(payload.data)))} · revision ${e(payload.view_revision)}${catalogError?' · 目录补充暂不可用':''}</span><span>未接入不等于零 · UNKNOWN 不等于健康${transportError?' · 最近已知帧，非当前结论':''}</span><span>COMPUTE OBSERVABILITY / ${n}</span>`;syncPause();}
function error(err){transportError=err.message;const snapshot=document.querySelector('.snapshot');if(snapshot)snapshot.textContent='通信中断 · 状态未知';if(payload)render();else app.innerHTML=`<div class="empty-state"><strong>${'等待统一数据源'}</strong><p>${e(err.message)}</p><a href="/gateway/">打开统一控制台 ↗</a></div>`;}
function header(){if(n==='01'){document.querySelector('#app-header').innerHTML=`<div class="app-bar"><a class="app-brand" href="01.html"><span class="brand-glyph">⌁</span><span><strong>智算运维 · 可观测中心</strong><small>COMPUTE OBSERVABILITY</small></span></a><nav class="app-nav">${Object.entries(titles).filter(([id])=>id!=='01').map(([id,t])=>`<a href="${id}.html"><span class="nav-number">${id}</span>${e(t)}</a>`).join('')}</nav><div class="header-actions"><span class="snapshot">正在加载</span><button class="header-button" id="pause">暂停 60s</button><button class="header-button" id="motion-toggle">动效</button><button class="header-button" id="full">全屏 ⛶</button></div></div>`;return;}document.querySelector('#app-header').innerHTML=`<div class="app-bar"><a class="app-brand" href="01.html"><span class="brand-glyph">⌁</span><span><strong>智算运维 · 可观测中心</strong><small>COMPUTE OBSERVABILITY</small></span></a><nav class="app-nav">${Object.entries(titles).filter(([id])=>id!=='01').map(([id,t])=>`<a href="${id}.html" class="${id===n?'active':''}"><span class="nav-number">${id}</span>${e(t)}</a>`).join('')}</nav><div class="header-actions"><span class="snapshot">正在加载</span><button class="header-button" id="pause">暂停 60s</button><button class="header-button" id="motion-toggle">动效</button><button class="header-button" id="full">全屏 ⛶</button></div></div>`;}
function fit(){const el=document.querySelector('.screen');if(innerWidth>1100||n==='01'){const scale=Math.min(innerWidth/1920,innerHeight/1080);el.style.transform=`scale(${scale})`;el.style.left=(innerWidth-1920*scale)/2+'px';el.style.top=(innerHeight-1080*scale)/2+'px';if(n==='01'){el.style.setProperty('transform',`scale(${scale})`,'important');el.style.setProperty('left',(innerWidth-1920*scale)/2+'px','important');el.style.setProperty('top',(innerHeight-1080*scale)/2+'px','important');}}else{el.style.transform='';el.style.left='';el.style.top='';}}
function updateMotion(){const enabled=motion&&!motionPreference.matches;document.body.classList.toggle('motion-paused',!enabled);const b=document.querySelector('#motion-toggle');if(b){b.textContent=enabled?'动效已开启':'动效已暂停';b.disabled=motionPreference.matches;b.setAttribute('aria-pressed',String(enabled));}}
motionPreference.addEventListener('change',updateMotion);header();fit();updateMotion();addEventListener('resize',fit);document.addEventListener('click',ev=>{if(ev.target.closest('#pause'))pause(!state.paused);if(ev.target.closest('#motion-toggle')){motion=!motion;updateMotion();}if(ev.target.closest('#full'))document.documentElement.requestFullscreen?.();});document.addEventListener('visibilitychange',()=>{document.body.classList.toggle('visibility-paused',document.hidden);if(document.hidden)hiddenAt=Date.now();else{if(hiddenAt&&state.manualUntil)state.manualUntil+=Date.now()-hiddenAt;hiddenAt=null;}});
async function loadCatalog(){if(catalogLoading)return;catalogLoading=true;const names=['clusters','services','models','businesses','endpoints','pd-groups','runtime-members'];const results=await Promise.allSettled(names.map(async name=>{let cursor='',rows=[],seen=new Set();do{const v=await A.request('/api/v1/catalog/'+name+'?limit=100'+(cursor?'&cursor='+encodeURIComponent(cursor):''));if(!Array.isArray(v.data?.items))throw new Error('目录响应无效');rows.push(...v.data.items);cursor=v.data.next_cursor;if(cursor&&seen.has(cursor))throw new Error('目录游标重复');seen.add(cursor);}while(cursor);return [name,rows.filter(x=>x.enabled!==false)];}));for(const result of results){if(result.status==='fulfilled')ctx.catalog[result.value[0]]=result.value[1];else catalogError='目录暂不可用';}catalogLoading=false;render();}
const timer=setInterval(()=>{ctx.now=Date.now();if(document.hidden)return;if(state.paused&&state.manualUntil&&ctx.now>=state.manualUntil)pause(false);if(ctx.data)window.ScreenRenderers?.[n]?.tick?.(ctx);const clock=document.querySelector('#sys-time');if(clock)clock.textContent=new Date().toLocaleString('zh-CN',{hour12:false});},1000);
(async()=>{try{await A.ensureAccess();const boot=await A.request('/api/v1/screens/bootstrap');if(boot.data.data_mode!=='live')throw new Error('仅接受统一 live 投影');await loadCatalog();provider=new LiveData.LiveProvider({path:'/api/v1/screens/'+paths[n],interval:Math.max(5,boot.data.refresh_seconds||10)*1000,onData:v=>{validate(v);const previous=payload;payload=v;try{render();}catch(err){payload=previous;throw err;}transportError='';render();loadCatalog();},onAge:()=>{if(!payload)return;const signature=JSON.stringify([LiveData.freshness(payload.data),...payload.data.items.flatMap(x=>(x.endpoints||[x]).map(x=>LiveData.endpointState(x)))]);if(signature!==lastAgeSignature){lastAgeSignature=signature;render();}},onError:error,onContact:()=>{if(transportError){transportError='';render();}}});provider.start();}catch(err){error(err);}})();
addEventListener('pagehide',()=>{provider?.stop();clearInterval(timer);});window.ScreenLive={ctx,ageState:LiveData.freshness,endpointState:LiveData.endpointState,get payload(){return payload;},get paused(){return state.paused;}};
})();
